// Code generated by go-swagger; DO NOT EDIT.

package subscription_package_order_manager

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewSubscriptionPackageOrderManagerGetPrdOrderParams creates a new SubscriptionPackageOrderManagerGetPrdOrderParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewSubscriptionPackageOrderManagerGetPrdOrderParams() *SubscriptionPackageOrderManagerGetPrdOrderParams {
	return &SubscriptionPackageOrderManagerGetPrdOrderParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewSubscriptionPackageOrderManagerGetPrdOrderParamsWithTimeout creates a new SubscriptionPackageOrderManagerGetPrdOrderParams object
// with the ability to set a timeout on a request.
func NewSubscriptionPackageOrderManagerGetPrdOrderParamsWithTimeout(timeout time.Duration) *SubscriptionPackageOrderManagerGetPrdOrderParams {
	return &SubscriptionPackageOrderManagerGetPrdOrderParams{
		timeout: timeout,
	}
}

// NewSubscriptionPackageOrderManagerGetPrdOrderParamsWithContext creates a new SubscriptionPackageOrderManagerGetPrdOrderParams object
// with the ability to set a context for a request.
func NewSubscriptionPackageOrderManagerGetPrdOrderParamsWithContext(ctx context.Context) *SubscriptionPackageOrderManagerGetPrdOrderParams {
	return &SubscriptionPackageOrderManagerGetPrdOrderParams{
		Context: ctx,
	}
}

// NewSubscriptionPackageOrderManagerGetPrdOrderParamsWithHTTPClient creates a new SubscriptionPackageOrderManagerGetPrdOrderParams object
// with the ability to set a custom HTTPClient for a request.
func NewSubscriptionPackageOrderManagerGetPrdOrderParamsWithHTTPClient(client *http.Client) *SubscriptionPackageOrderManagerGetPrdOrderParams {
	return &SubscriptionPackageOrderManagerGetPrdOrderParams{
		HTTPClient: client,
	}
}

/*
SubscriptionPackageOrderManagerGetPrdOrderParams contains all the parameters to send to the API endpoint

	for the subscription package order manager get prd order operation.

	Typically these are written to a http.Request.
*/
type SubscriptionPackageOrderManagerGetPrdOrderParams struct {

	// OrderID.
	OrderID string

	/* Simplify.

	   是否返回最简信息 默认值false.
	*/
	Simplify *bool

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the subscription package order manager get prd order params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SubscriptionPackageOrderManagerGetPrdOrderParams) WithDefaults() *SubscriptionPackageOrderManagerGetPrdOrderParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the subscription package order manager get prd order params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SubscriptionPackageOrderManagerGetPrdOrderParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the subscription package order manager get prd order params
func (o *SubscriptionPackageOrderManagerGetPrdOrderParams) WithTimeout(timeout time.Duration) *SubscriptionPackageOrderManagerGetPrdOrderParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the subscription package order manager get prd order params
func (o *SubscriptionPackageOrderManagerGetPrdOrderParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the subscription package order manager get prd order params
func (o *SubscriptionPackageOrderManagerGetPrdOrderParams) WithContext(ctx context.Context) *SubscriptionPackageOrderManagerGetPrdOrderParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the subscription package order manager get prd order params
func (o *SubscriptionPackageOrderManagerGetPrdOrderParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the subscription package order manager get prd order params
func (o *SubscriptionPackageOrderManagerGetPrdOrderParams) WithHTTPClient(client *http.Client) *SubscriptionPackageOrderManagerGetPrdOrderParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the subscription package order manager get prd order params
func (o *SubscriptionPackageOrderManagerGetPrdOrderParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithOrderID adds the orderID to the subscription package order manager get prd order params
func (o *SubscriptionPackageOrderManagerGetPrdOrderParams) WithOrderID(orderID string) *SubscriptionPackageOrderManagerGetPrdOrderParams {
	o.SetOrderID(orderID)
	return o
}

// SetOrderID adds the orderId to the subscription package order manager get prd order params
func (o *SubscriptionPackageOrderManagerGetPrdOrderParams) SetOrderID(orderID string) {
	o.OrderID = orderID
}

// WithSimplify adds the simplify to the subscription package order manager get prd order params
func (o *SubscriptionPackageOrderManagerGetPrdOrderParams) WithSimplify(simplify *bool) *SubscriptionPackageOrderManagerGetPrdOrderParams {
	o.SetSimplify(simplify)
	return o
}

// SetSimplify adds the simplify to the subscription package order manager get prd order params
func (o *SubscriptionPackageOrderManagerGetPrdOrderParams) SetSimplify(simplify *bool) {
	o.Simplify = simplify
}

// WriteToRequest writes these params to a swagger request
func (o *SubscriptionPackageOrderManagerGetPrdOrderParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param order_id
	if err := r.SetPathParam("order_id", o.OrderID); err != nil {
		return err
	}

	if o.Simplify != nil {

		// query param simplify
		var qrSimplify bool

		if o.Simplify != nil {
			qrSimplify = *o.Simplify
		}
		qSimplify := swag.FormatBool(qrSimplify)
		if qSimplify != "" {

			if err := r.SetQueryParam("simplify", qSimplify); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
