// Code generated by go-swagger; DO NOT EDIT.

package subscription_package_order_manager

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/KubeSphereCloud/newbilling-client-go/models"
)

// SubscriptionPackageOrderManagerGetPrdOrderReader is a Reader for the SubscriptionPackageOrderManagerGetPrdOrder structure.
type SubscriptionPackageOrderManagerGetPrdOrderReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SubscriptionPackageOrderManagerGetPrdOrderReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewSubscriptionPackageOrderManagerGetPrdOrderOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewSubscriptionPackageOrderManagerGetPrdOrderDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewSubscriptionPackageOrderManagerGetPrdOrderOK creates a SubscriptionPackageOrderManagerGetPrdOrderOK with default headers values
func NewSubscriptionPackageOrderManagerGetPrdOrderOK() *SubscriptionPackageOrderManagerGetPrdOrderOK {
	return &SubscriptionPackageOrderManagerGetPrdOrderOK{}
}

/*
SubscriptionPackageOrderManagerGetPrdOrderOK describes a response with status code 200, with default header values.

A successful response.
*/
type SubscriptionPackageOrderManagerGetPrdOrderOK struct {
	Payload *models.NewbillingGetPrdOrderResponse
}

// IsSuccess returns true when this subscription package order manager get prd order o k response has a 2xx status code
func (o *SubscriptionPackageOrderManagerGetPrdOrderOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this subscription package order manager get prd order o k response has a 3xx status code
func (o *SubscriptionPackageOrderManagerGetPrdOrderOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this subscription package order manager get prd order o k response has a 4xx status code
func (o *SubscriptionPackageOrderManagerGetPrdOrderOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this subscription package order manager get prd order o k response has a 5xx status code
func (o *SubscriptionPackageOrderManagerGetPrdOrderOK) IsServerError() bool {
	return false
}

// IsCode returns true when this subscription package order manager get prd order o k response a status code equal to that given
func (o *SubscriptionPackageOrderManagerGetPrdOrderOK) IsCode(code int) bool {
	return code == 200
}

func (o *SubscriptionPackageOrderManagerGetPrdOrderOK) Error() string {
	return fmt.Sprintf("[GET /v1/packageorders/{order_id}][%d] subscriptionPackageOrderManagerGetPrdOrderOK  %+v", 200, o.Payload)
}

func (o *SubscriptionPackageOrderManagerGetPrdOrderOK) String() string {
	return fmt.Sprintf("[GET /v1/packageorders/{order_id}][%d] subscriptionPackageOrderManagerGetPrdOrderOK  %+v", 200, o.Payload)
}

func (o *SubscriptionPackageOrderManagerGetPrdOrderOK) GetPayload() *models.NewbillingGetPrdOrderResponse {
	return o.Payload
}

func (o *SubscriptionPackageOrderManagerGetPrdOrderOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.NewbillingGetPrdOrderResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSubscriptionPackageOrderManagerGetPrdOrderDefault creates a SubscriptionPackageOrderManagerGetPrdOrderDefault with default headers values
func NewSubscriptionPackageOrderManagerGetPrdOrderDefault(code int) *SubscriptionPackageOrderManagerGetPrdOrderDefault {
	return &SubscriptionPackageOrderManagerGetPrdOrderDefault{
		_statusCode: code,
	}
}

/*
SubscriptionPackageOrderManagerGetPrdOrderDefault describes a response with status code -1, with default header values.

An unexpected error response
*/
type SubscriptionPackageOrderManagerGetPrdOrderDefault struct {
	_statusCode int

	Payload *models.RuntimeError
}

// Code gets the status code for the subscription package order manager get prd order default response
func (o *SubscriptionPackageOrderManagerGetPrdOrderDefault) Code() int {
	return o._statusCode
}

// IsSuccess returns true when this subscription package order manager get prd order default response has a 2xx status code
func (o *SubscriptionPackageOrderManagerGetPrdOrderDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this subscription package order manager get prd order default response has a 3xx status code
func (o *SubscriptionPackageOrderManagerGetPrdOrderDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this subscription package order manager get prd order default response has a 4xx status code
func (o *SubscriptionPackageOrderManagerGetPrdOrderDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this subscription package order manager get prd order default response has a 5xx status code
func (o *SubscriptionPackageOrderManagerGetPrdOrderDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this subscription package order manager get prd order default response a status code equal to that given
func (o *SubscriptionPackageOrderManagerGetPrdOrderDefault) IsCode(code int) bool {
	return o._statusCode == code
}

func (o *SubscriptionPackageOrderManagerGetPrdOrderDefault) Error() string {
	return fmt.Sprintf("[GET /v1/packageorders/{order_id}][%d] SubscriptionPackageOrderManager_GetPrdOrder default  %+v", o._statusCode, o.Payload)
}

func (o *SubscriptionPackageOrderManagerGetPrdOrderDefault) String() string {
	return fmt.Sprintf("[GET /v1/packageorders/{order_id}][%d] SubscriptionPackageOrderManager_GetPrdOrder default  %+v", o._statusCode, o.Payload)
}

func (o *SubscriptionPackageOrderManagerGetPrdOrderDefault) GetPayload() *models.RuntimeError {
	return o.Payload
}

func (o *SubscriptionPackageOrderManagerGetPrdOrderDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RuntimeError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
