// Code generated by go-swagger; DO NOT EDIT.

package pricing_cost_manager

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/KubeSphereCloud/newbilling-client-go/models"
)

// NewPricingCostManagerCalculateProductPriceParams creates a new PricingCostManagerCalculateProductPriceParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPricingCostManagerCalculateProductPriceParams() *PricingCostManagerCalculateProductPriceParams {
	return &PricingCostManagerCalculateProductPriceParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPricingCostManagerCalculateProductPriceParamsWithTimeout creates a new PricingCostManagerCalculateProductPriceParams object
// with the ability to set a timeout on a request.
func NewPricingCostManagerCalculateProductPriceParamsWithTimeout(timeout time.Duration) *PricingCostManagerCalculateProductPriceParams {
	return &PricingCostManagerCalculateProductPriceParams{
		timeout: timeout,
	}
}

// NewPricingCostManagerCalculateProductPriceParamsWithContext creates a new PricingCostManagerCalculateProductPriceParams object
// with the ability to set a context for a request.
func NewPricingCostManagerCalculateProductPriceParamsWithContext(ctx context.Context) *PricingCostManagerCalculateProductPriceParams {
	return &PricingCostManagerCalculateProductPriceParams{
		Context: ctx,
	}
}

// NewPricingCostManagerCalculateProductPriceParamsWithHTTPClient creates a new PricingCostManagerCalculateProductPriceParams object
// with the ability to set a custom HTTPClient for a request.
func NewPricingCostManagerCalculateProductPriceParamsWithHTTPClient(client *http.Client) *PricingCostManagerCalculateProductPriceParams {
	return &PricingCostManagerCalculateProductPriceParams{
		HTTPClient: client,
	}
}

/*
PricingCostManagerCalculateProductPriceParams contains all the parameters to send to the API endpoint

	for the pricing cost manager calculate product price operation.

	Typically these are written to a http.Request.
*/
type PricingCostManagerCalculateProductPriceParams struct {

	// Body.
	Body *models.NewbillingCalculateProductPriceRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the pricing cost manager calculate product price params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PricingCostManagerCalculateProductPriceParams) WithDefaults() *PricingCostManagerCalculateProductPriceParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the pricing cost manager calculate product price params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PricingCostManagerCalculateProductPriceParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the pricing cost manager calculate product price params
func (o *PricingCostManagerCalculateProductPriceParams) WithTimeout(timeout time.Duration) *PricingCostManagerCalculateProductPriceParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the pricing cost manager calculate product price params
func (o *PricingCostManagerCalculateProductPriceParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the pricing cost manager calculate product price params
func (o *PricingCostManagerCalculateProductPriceParams) WithContext(ctx context.Context) *PricingCostManagerCalculateProductPriceParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the pricing cost manager calculate product price params
func (o *PricingCostManagerCalculateProductPriceParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the pricing cost manager calculate product price params
func (o *PricingCostManagerCalculateProductPriceParams) WithHTTPClient(client *http.Client) *PricingCostManagerCalculateProductPriceParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the pricing cost manager calculate product price params
func (o *PricingCostManagerCalculateProductPriceParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the pricing cost manager calculate product price params
func (o *PricingCostManagerCalculateProductPriceParams) WithBody(body *models.NewbillingCalculateProductPriceRequest) *PricingCostManagerCalculateProductPriceParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the pricing cost manager calculate product price params
func (o *PricingCostManagerCalculateProductPriceParams) SetBody(body *models.NewbillingCalculateProductPriceRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *PricingCostManagerCalculateProductPriceParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
