// Code generated by go-swagger; DO NOT EDIT.

package service_manager

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/KubeSphereCloud/newbilling-client-go/models"
)

// NewServiceManagerModifyServiceParams creates a new ServiceManagerModifyServiceParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewServiceManagerModifyServiceParams() *ServiceManagerModifyServiceParams {
	return &ServiceManagerModifyServiceParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewServiceManagerModifyServiceParamsWithTimeout creates a new ServiceManagerModifyServiceParams object
// with the ability to set a timeout on a request.
func NewServiceManagerModifyServiceParamsWithTimeout(timeout time.Duration) *ServiceManagerModifyServiceParams {
	return &ServiceManagerModifyServiceParams{
		timeout: timeout,
	}
}

// NewServiceManagerModifyServiceParamsWithContext creates a new ServiceManagerModifyServiceParams object
// with the ability to set a context for a request.
func NewServiceManagerModifyServiceParamsWithContext(ctx context.Context) *ServiceManagerModifyServiceParams {
	return &ServiceManagerModifyServiceParams{
		Context: ctx,
	}
}

// NewServiceManagerModifyServiceParamsWithHTTPClient creates a new ServiceManagerModifyServiceParams object
// with the ability to set a custom HTTPClient for a request.
func NewServiceManagerModifyServiceParamsWithHTTPClient(client *http.Client) *ServiceManagerModifyServiceParams {
	return &ServiceManagerModifyServiceParams{
		HTTPClient: client,
	}
}

/*
ServiceManagerModifyServiceParams contains all the parameters to send to the API endpoint

	for the service manager modify service operation.

	Typically these are written to a http.Request.
*/
type ServiceManagerModifyServiceParams struct {

	// Body.
	Body *models.NewbillingModifyServiceRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the service manager modify service params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ServiceManagerModifyServiceParams) WithDefaults() *ServiceManagerModifyServiceParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the service manager modify service params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ServiceManagerModifyServiceParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the service manager modify service params
func (o *ServiceManagerModifyServiceParams) WithTimeout(timeout time.Duration) *ServiceManagerModifyServiceParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the service manager modify service params
func (o *ServiceManagerModifyServiceParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the service manager modify service params
func (o *ServiceManagerModifyServiceParams) WithContext(ctx context.Context) *ServiceManagerModifyServiceParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the service manager modify service params
func (o *ServiceManagerModifyServiceParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the service manager modify service params
func (o *ServiceManagerModifyServiceParams) WithHTTPClient(client *http.Client) *ServiceManagerModifyServiceParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the service manager modify service params
func (o *ServiceManagerModifyServiceParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the service manager modify service params
func (o *ServiceManagerModifyServiceParams) WithBody(body *models.NewbillingModifyServiceRequest) *ServiceManagerModifyServiceParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the service manager modify service params
func (o *ServiceManagerModifyServiceParams) SetBody(body *models.NewbillingModifyServiceRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *ServiceManagerModifyServiceParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
