// Code generated by go-swagger; DO NOT EDIT.

package customer_manager

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/KubeSphereCloud/newbilling-client-go/models"
)

// NewCustomerManagerCreateOrUpdateCustomerParams creates a new CustomerManagerCreateOrUpdateCustomerParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCustomerManagerCreateOrUpdateCustomerParams() *CustomerManagerCreateOrUpdateCustomerParams {
	return &CustomerManagerCreateOrUpdateCustomerParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCustomerManagerCreateOrUpdateCustomerParamsWithTimeout creates a new CustomerManagerCreateOrUpdateCustomerParams object
// with the ability to set a timeout on a request.
func NewCustomerManagerCreateOrUpdateCustomerParamsWithTimeout(timeout time.Duration) *CustomerManagerCreateOrUpdateCustomerParams {
	return &CustomerManagerCreateOrUpdateCustomerParams{
		timeout: timeout,
	}
}

// NewCustomerManagerCreateOrUpdateCustomerParamsWithContext creates a new CustomerManagerCreateOrUpdateCustomerParams object
// with the ability to set a context for a request.
func NewCustomerManagerCreateOrUpdateCustomerParamsWithContext(ctx context.Context) *CustomerManagerCreateOrUpdateCustomerParams {
	return &CustomerManagerCreateOrUpdateCustomerParams{
		Context: ctx,
	}
}

// NewCustomerManagerCreateOrUpdateCustomerParamsWithHTTPClient creates a new CustomerManagerCreateOrUpdateCustomerParams object
// with the ability to set a custom HTTPClient for a request.
func NewCustomerManagerCreateOrUpdateCustomerParamsWithHTTPClient(client *http.Client) *CustomerManagerCreateOrUpdateCustomerParams {
	return &CustomerManagerCreateOrUpdateCustomerParams{
		HTTPClient: client,
	}
}

/*
CustomerManagerCreateOrUpdateCustomerParams contains all the parameters to send to the API endpoint

	for the customer manager create or update customer operation.

	Typically these are written to a http.Request.
*/
type CustomerManagerCreateOrUpdateCustomerParams struct {

	// Body.
	Body *models.NewbillingCreateOrUpdateCustomerRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the customer manager create or update customer params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CustomerManagerCreateOrUpdateCustomerParams) WithDefaults() *CustomerManagerCreateOrUpdateCustomerParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the customer manager create or update customer params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CustomerManagerCreateOrUpdateCustomerParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the customer manager create or update customer params
func (o *CustomerManagerCreateOrUpdateCustomerParams) WithTimeout(timeout time.Duration) *CustomerManagerCreateOrUpdateCustomerParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the customer manager create or update customer params
func (o *CustomerManagerCreateOrUpdateCustomerParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the customer manager create or update customer params
func (o *CustomerManagerCreateOrUpdateCustomerParams) WithContext(ctx context.Context) *CustomerManagerCreateOrUpdateCustomerParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the customer manager create or update customer params
func (o *CustomerManagerCreateOrUpdateCustomerParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the customer manager create or update customer params
func (o *CustomerManagerCreateOrUpdateCustomerParams) WithHTTPClient(client *http.Client) *CustomerManagerCreateOrUpdateCustomerParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the customer manager create or update customer params
func (o *CustomerManagerCreateOrUpdateCustomerParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the customer manager create or update customer params
func (o *CustomerManagerCreateOrUpdateCustomerParams) WithBody(body *models.NewbillingCreateOrUpdateCustomerRequest) *CustomerManagerCreateOrUpdateCustomerParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the customer manager create or update customer params
func (o *CustomerManagerCreateOrUpdateCustomerParams) SetBody(body *models.NewbillingCreateOrUpdateCustomerRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *CustomerManagerCreateOrUpdateCustomerParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
