// Code generated by go-swagger; DO NOT EDIT.

package discount_manager

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/KubeSphereCloud/newbilling-client-go/models"
)

// DiscountManagerModifyCustomerDiscountReader is a Reader for the DiscountManagerModifyCustomerDiscount structure.
type DiscountManagerModifyCustomerDiscountReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DiscountManagerModifyCustomerDiscountReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDiscountManagerModifyCustomerDiscountOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewDiscountManagerModifyCustomerDiscountDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewDiscountManagerModifyCustomerDiscountOK creates a DiscountManagerModifyCustomerDiscountOK with default headers values
func NewDiscountManagerModifyCustomerDiscountOK() *DiscountManagerModifyCustomerDiscountOK {
	return &DiscountManagerModifyCustomerDiscountOK{}
}

/*
DiscountManagerModifyCustomerDiscountOK describes a response with status code 200, with default header values.

A successful response.
*/
type DiscountManagerModifyCustomerDiscountOK struct {
	Payload *models.NewbillingModifyCustomerDiscountResponse
}

// IsSuccess returns true when this discount manager modify customer discount o k response has a 2xx status code
func (o *DiscountManagerModifyCustomerDiscountOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this discount manager modify customer discount o k response has a 3xx status code
func (o *DiscountManagerModifyCustomerDiscountOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this discount manager modify customer discount o k response has a 4xx status code
func (o *DiscountManagerModifyCustomerDiscountOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this discount manager modify customer discount o k response has a 5xx status code
func (o *DiscountManagerModifyCustomerDiscountOK) IsServerError() bool {
	return false
}

// IsCode returns true when this discount manager modify customer discount o k response a status code equal to that given
func (o *DiscountManagerModifyCustomerDiscountOK) IsCode(code int) bool {
	return code == 200
}

func (o *DiscountManagerModifyCustomerDiscountOK) Error() string {
	return fmt.Sprintf("[PATCH /v1/customerdiscounts][%d] discountManagerModifyCustomerDiscountOK  %+v", 200, o.Payload)
}

func (o *DiscountManagerModifyCustomerDiscountOK) String() string {
	return fmt.Sprintf("[PATCH /v1/customerdiscounts][%d] discountManagerModifyCustomerDiscountOK  %+v", 200, o.Payload)
}

func (o *DiscountManagerModifyCustomerDiscountOK) GetPayload() *models.NewbillingModifyCustomerDiscountResponse {
	return o.Payload
}

func (o *DiscountManagerModifyCustomerDiscountOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.NewbillingModifyCustomerDiscountResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDiscountManagerModifyCustomerDiscountDefault creates a DiscountManagerModifyCustomerDiscountDefault with default headers values
func NewDiscountManagerModifyCustomerDiscountDefault(code int) *DiscountManagerModifyCustomerDiscountDefault {
	return &DiscountManagerModifyCustomerDiscountDefault{
		_statusCode: code,
	}
}

/*
DiscountManagerModifyCustomerDiscountDefault describes a response with status code -1, with default header values.

An unexpected error response
*/
type DiscountManagerModifyCustomerDiscountDefault struct {
	_statusCode int

	Payload *models.RuntimeError
}

// Code gets the status code for the discount manager modify customer discount default response
func (o *DiscountManagerModifyCustomerDiscountDefault) Code() int {
	return o._statusCode
}

// IsSuccess returns true when this discount manager modify customer discount default response has a 2xx status code
func (o *DiscountManagerModifyCustomerDiscountDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this discount manager modify customer discount default response has a 3xx status code
func (o *DiscountManagerModifyCustomerDiscountDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this discount manager modify customer discount default response has a 4xx status code
func (o *DiscountManagerModifyCustomerDiscountDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this discount manager modify customer discount default response has a 5xx status code
func (o *DiscountManagerModifyCustomerDiscountDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this discount manager modify customer discount default response a status code equal to that given
func (o *DiscountManagerModifyCustomerDiscountDefault) IsCode(code int) bool {
	return o._statusCode == code
}

func (o *DiscountManagerModifyCustomerDiscountDefault) Error() string {
	return fmt.Sprintf("[PATCH /v1/customerdiscounts][%d] DiscountManager_ModifyCustomerDiscount default  %+v", o._statusCode, o.Payload)
}

func (o *DiscountManagerModifyCustomerDiscountDefault) String() string {
	return fmt.Sprintf("[PATCH /v1/customerdiscounts][%d] DiscountManager_ModifyCustomerDiscount default  %+v", o._statusCode, o.Payload)
}

func (o *DiscountManagerModifyCustomerDiscountDefault) GetPayload() *models.RuntimeError {
	return o.Payload
}

func (o *DiscountManagerModifyCustomerDiscountDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RuntimeError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
