// Code generated by go-swagger; DO NOT EDIT.

package discount_manager

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/KubeSphereCloud/newbilling-client-go/models"
)

// NewDiscountManagerCalculateCustomerDiscountParams creates a new DiscountManagerCalculateCustomerDiscountParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDiscountManagerCalculateCustomerDiscountParams() *DiscountManagerCalculateCustomerDiscountParams {
	return &DiscountManagerCalculateCustomerDiscountParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDiscountManagerCalculateCustomerDiscountParamsWithTimeout creates a new DiscountManagerCalculateCustomerDiscountParams object
// with the ability to set a timeout on a request.
func NewDiscountManagerCalculateCustomerDiscountParamsWithTimeout(timeout time.Duration) *DiscountManagerCalculateCustomerDiscountParams {
	return &DiscountManagerCalculateCustomerDiscountParams{
		timeout: timeout,
	}
}

// NewDiscountManagerCalculateCustomerDiscountParamsWithContext creates a new DiscountManagerCalculateCustomerDiscountParams object
// with the ability to set a context for a request.
func NewDiscountManagerCalculateCustomerDiscountParamsWithContext(ctx context.Context) *DiscountManagerCalculateCustomerDiscountParams {
	return &DiscountManagerCalculateCustomerDiscountParams{
		Context: ctx,
	}
}

// NewDiscountManagerCalculateCustomerDiscountParamsWithHTTPClient creates a new DiscountManagerCalculateCustomerDiscountParams object
// with the ability to set a custom HTTPClient for a request.
func NewDiscountManagerCalculateCustomerDiscountParamsWithHTTPClient(client *http.Client) *DiscountManagerCalculateCustomerDiscountParams {
	return &DiscountManagerCalculateCustomerDiscountParams{
		HTTPClient: client,
	}
}

/*
DiscountManagerCalculateCustomerDiscountParams contains all the parameters to send to the API endpoint

	for the discount manager calculate customer discount operation.

	Typically these are written to a http.Request.
*/
type DiscountManagerCalculateCustomerDiscountParams struct {

	// Body.
	Body *models.NewbillingCalculateCustomerDiscountRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the discount manager calculate customer discount params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DiscountManagerCalculateCustomerDiscountParams) WithDefaults() *DiscountManagerCalculateCustomerDiscountParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the discount manager calculate customer discount params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DiscountManagerCalculateCustomerDiscountParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the discount manager calculate customer discount params
func (o *DiscountManagerCalculateCustomerDiscountParams) WithTimeout(timeout time.Duration) *DiscountManagerCalculateCustomerDiscountParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the discount manager calculate customer discount params
func (o *DiscountManagerCalculateCustomerDiscountParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the discount manager calculate customer discount params
func (o *DiscountManagerCalculateCustomerDiscountParams) WithContext(ctx context.Context) *DiscountManagerCalculateCustomerDiscountParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the discount manager calculate customer discount params
func (o *DiscountManagerCalculateCustomerDiscountParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the discount manager calculate customer discount params
func (o *DiscountManagerCalculateCustomerDiscountParams) WithHTTPClient(client *http.Client) *DiscountManagerCalculateCustomerDiscountParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the discount manager calculate customer discount params
func (o *DiscountManagerCalculateCustomerDiscountParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the discount manager calculate customer discount params
func (o *DiscountManagerCalculateCustomerDiscountParams) WithBody(body *models.NewbillingCalculateCustomerDiscountRequest) *DiscountManagerCalculateCustomerDiscountParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the discount manager calculate customer discount params
func (o *DiscountManagerCalculateCustomerDiscountParams) SetBody(body *models.NewbillingCalculateCustomerDiscountRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *DiscountManagerCalculateCustomerDiscountParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
