// Code generated by go-swagger; DO NOT EDIT.

package iam_manager4_appcenter

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new iam manager4 appcenter API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for iam manager4 appcenter API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption is the option for Client methods
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	IamManager4AppcenterDeleteOpenToken(params *IamManager4AppcenterDeleteOpenTokenParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*IamManager4AppcenterDeleteOpenTokenOK, error)

	IamManager4AppcenterRefreshOpenToken(params *IamManager4AppcenterRefreshOpenTokenParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*IamManager4AppcenterRefreshOpenTokenOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
IamManager4AppcenterDeleteOpenToken appcenter专用接口s 提供给 appcenter删除token的接口
*/
func (a *Client) IamManager4AppcenterDeleteOpenToken(params *IamManager4AppcenterDeleteOpenTokenParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*IamManager4AppcenterDeleteOpenTokenOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewIamManager4AppcenterDeleteOpenTokenParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "IamManager4Appcenter_DeleteOpenToken",
		Method:             "POST",
		PathPattern:        "/v1/open/token:delete",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &IamManager4AppcenterDeleteOpenTokenReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*IamManager4AppcenterDeleteOpenTokenOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*IamManager4AppcenterDeleteOpenTokenDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
IamManager4AppcenterRefreshOpenToken appcenter专用接口s 提供给 appcenter的刷新token的接口
*/
func (a *Client) IamManager4AppcenterRefreshOpenToken(params *IamManager4AppcenterRefreshOpenTokenParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*IamManager4AppcenterRefreshOpenTokenOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewIamManager4AppcenterRefreshOpenTokenParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "IamManager4Appcenter_RefreshOpenToken",
		Method:             "POST",
		PathPattern:        "/v1/open/token:refresh",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &IamManager4AppcenterRefreshOpenTokenReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*IamManager4AppcenterRefreshOpenTokenOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*IamManager4AppcenterRefreshOpenTokenDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
