// Code generated by go-swagger; DO NOT EDIT.

package iam_manager4_appcenter

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/KubeSphereCloud/newbilling-client-go/models"
)

// NewIamManager4AppcenterDeleteOpenTokenParams creates a new IamManager4AppcenterDeleteOpenTokenParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewIamManager4AppcenterDeleteOpenTokenParams() *IamManager4AppcenterDeleteOpenTokenParams {
	return &IamManager4AppcenterDeleteOpenTokenParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewIamManager4AppcenterDeleteOpenTokenParamsWithTimeout creates a new IamManager4AppcenterDeleteOpenTokenParams object
// with the ability to set a timeout on a request.
func NewIamManager4AppcenterDeleteOpenTokenParamsWithTimeout(timeout time.Duration) *IamManager4AppcenterDeleteOpenTokenParams {
	return &IamManager4AppcenterDeleteOpenTokenParams{
		timeout: timeout,
	}
}

// NewIamManager4AppcenterDeleteOpenTokenParamsWithContext creates a new IamManager4AppcenterDeleteOpenTokenParams object
// with the ability to set a context for a request.
func NewIamManager4AppcenterDeleteOpenTokenParamsWithContext(ctx context.Context) *IamManager4AppcenterDeleteOpenTokenParams {
	return &IamManager4AppcenterDeleteOpenTokenParams{
		Context: ctx,
	}
}

// NewIamManager4AppcenterDeleteOpenTokenParamsWithHTTPClient creates a new IamManager4AppcenterDeleteOpenTokenParams object
// with the ability to set a custom HTTPClient for a request.
func NewIamManager4AppcenterDeleteOpenTokenParamsWithHTTPClient(client *http.Client) *IamManager4AppcenterDeleteOpenTokenParams {
	return &IamManager4AppcenterDeleteOpenTokenParams{
		HTTPClient: client,
	}
}

/*
IamManager4AppcenterDeleteOpenTokenParams contains all the parameters to send to the API endpoint

	for the iam manager4 appcenter delete open token operation.

	Typically these are written to a http.Request.
*/
type IamManager4AppcenterDeleteOpenTokenParams struct {

	// Body.
	Body *models.NewbillingDeleteOpenTokenRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the iam manager4 appcenter delete open token params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *IamManager4AppcenterDeleteOpenTokenParams) WithDefaults() *IamManager4AppcenterDeleteOpenTokenParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the iam manager4 appcenter delete open token params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *IamManager4AppcenterDeleteOpenTokenParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the iam manager4 appcenter delete open token params
func (o *IamManager4AppcenterDeleteOpenTokenParams) WithTimeout(timeout time.Duration) *IamManager4AppcenterDeleteOpenTokenParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the iam manager4 appcenter delete open token params
func (o *IamManager4AppcenterDeleteOpenTokenParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the iam manager4 appcenter delete open token params
func (o *IamManager4AppcenterDeleteOpenTokenParams) WithContext(ctx context.Context) *IamManager4AppcenterDeleteOpenTokenParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the iam manager4 appcenter delete open token params
func (o *IamManager4AppcenterDeleteOpenTokenParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the iam manager4 appcenter delete open token params
func (o *IamManager4AppcenterDeleteOpenTokenParams) WithHTTPClient(client *http.Client) *IamManager4AppcenterDeleteOpenTokenParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the iam manager4 appcenter delete open token params
func (o *IamManager4AppcenterDeleteOpenTokenParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the iam manager4 appcenter delete open token params
func (o *IamManager4AppcenterDeleteOpenTokenParams) WithBody(body *models.NewbillingDeleteOpenTokenRequest) *IamManager4AppcenterDeleteOpenTokenParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the iam manager4 appcenter delete open token params
func (o *IamManager4AppcenterDeleteOpenTokenParams) SetBody(body *models.NewbillingDeleteOpenTokenRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *IamManager4AppcenterDeleteOpenTokenParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
