// Code generated by go-swagger; DO NOT EDIT.

package notifier

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/KubeSphereCloud/newbilling-client-go/models"
)

// NotifierDescribeEventsReader is a Reader for the NotifierDescribeEvents structure.
type NotifierDescribeEventsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *NotifierDescribeEventsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewNotifierDescribeEventsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewNotifierDescribeEventsDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewNotifierDescribeEventsOK creates a NotifierDescribeEventsOK with default headers values
func NewNotifierDescribeEventsOK() *NotifierDescribeEventsOK {
	return &NotifierDescribeEventsOK{}
}

/*
NotifierDescribeEventsOK describes a response with status code 200, with default header values.

A successful response.
*/
type NotifierDescribeEventsOK struct {
	Payload *models.NewbillingDescribeEventsResponse
}

// IsSuccess returns true when this notifier describe events o k response has a 2xx status code
func (o *NotifierDescribeEventsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this notifier describe events o k response has a 3xx status code
func (o *NotifierDescribeEventsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this notifier describe events o k response has a 4xx status code
func (o *NotifierDescribeEventsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this notifier describe events o k response has a 5xx status code
func (o *NotifierDescribeEventsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this notifier describe events o k response a status code equal to that given
func (o *NotifierDescribeEventsOK) IsCode(code int) bool {
	return code == 200
}

func (o *NotifierDescribeEventsOK) Error() string {
	return fmt.Sprintf("[GET /v1/events][%d] notifierDescribeEventsOK  %+v", 200, o.Payload)
}

func (o *NotifierDescribeEventsOK) String() string {
	return fmt.Sprintf("[GET /v1/events][%d] notifierDescribeEventsOK  %+v", 200, o.Payload)
}

func (o *NotifierDescribeEventsOK) GetPayload() *models.NewbillingDescribeEventsResponse {
	return o.Payload
}

func (o *NotifierDescribeEventsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.NewbillingDescribeEventsResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewNotifierDescribeEventsDefault creates a NotifierDescribeEventsDefault with default headers values
func NewNotifierDescribeEventsDefault(code int) *NotifierDescribeEventsDefault {
	return &NotifierDescribeEventsDefault{
		_statusCode: code,
	}
}

/*
NotifierDescribeEventsDefault describes a response with status code -1, with default header values.

An unexpected error response
*/
type NotifierDescribeEventsDefault struct {
	_statusCode int

	Payload *models.RuntimeError
}

// Code gets the status code for the notifier describe events default response
func (o *NotifierDescribeEventsDefault) Code() int {
	return o._statusCode
}

// IsSuccess returns true when this notifier describe events default response has a 2xx status code
func (o *NotifierDescribeEventsDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this notifier describe events default response has a 3xx status code
func (o *NotifierDescribeEventsDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this notifier describe events default response has a 4xx status code
func (o *NotifierDescribeEventsDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this notifier describe events default response has a 5xx status code
func (o *NotifierDescribeEventsDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this notifier describe events default response a status code equal to that given
func (o *NotifierDescribeEventsDefault) IsCode(code int) bool {
	return o._statusCode == code
}

func (o *NotifierDescribeEventsDefault) Error() string {
	return fmt.Sprintf("[GET /v1/events][%d] Notifier_DescribeEvents default  %+v", o._statusCode, o.Payload)
}

func (o *NotifierDescribeEventsDefault) String() string {
	return fmt.Sprintf("[GET /v1/events][%d] Notifier_DescribeEvents default  %+v", o._statusCode, o.Payload)
}

func (o *NotifierDescribeEventsDefault) GetPayload() *models.RuntimeError {
	return o.Payload
}

func (o *NotifierDescribeEventsDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RuntimeError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
