// Code generated by go-swagger; DO NOT EDIT.

package notifier

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/KubeSphereCloud/newbilling-client-go/models"
)

// NotifierGetEmailServiceConfigReader is a Reader for the NotifierGetEmailServiceConfig structure.
type NotifierGetEmailServiceConfigReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *NotifierGetEmailServiceConfigReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewNotifierGetEmailServiceConfigOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewNotifierGetEmailServiceConfigDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewNotifierGetEmailServiceConfigOK creates a NotifierGetEmailServiceConfigOK with default headers values
func NewNotifierGetEmailServiceConfigOK() *NotifierGetEmailServiceConfigOK {
	return &NotifierGetEmailServiceConfigOK{}
}

/*
NotifierGetEmailServiceConfigOK describes a response with status code 200, with default header values.

A successful response.
*/
type NotifierGetEmailServiceConfigOK struct {
	Payload *models.NewbillingGetEmailServiceConfigResponse
}

// IsSuccess returns true when this notifier get email service config o k response has a 2xx status code
func (o *NotifierGetEmailServiceConfigOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this notifier get email service config o k response has a 3xx status code
func (o *NotifierGetEmailServiceConfigOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this notifier get email service config o k response has a 4xx status code
func (o *NotifierGetEmailServiceConfigOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this notifier get email service config o k response has a 5xx status code
func (o *NotifierGetEmailServiceConfigOK) IsServerError() bool {
	return false
}

// IsCode returns true when this notifier get email service config o k response a status code equal to that given
func (o *NotifierGetEmailServiceConfigOK) IsCode(code int) bool {
	return code == 200
}

func (o *NotifierGetEmailServiceConfigOK) Error() string {
	return fmt.Sprintf("[GET /v1/emailserviceconfig][%d] notifierGetEmailServiceConfigOK  %+v", 200, o.Payload)
}

func (o *NotifierGetEmailServiceConfigOK) String() string {
	return fmt.Sprintf("[GET /v1/emailserviceconfig][%d] notifierGetEmailServiceConfigOK  %+v", 200, o.Payload)
}

func (o *NotifierGetEmailServiceConfigOK) GetPayload() *models.NewbillingGetEmailServiceConfigResponse {
	return o.Payload
}

func (o *NotifierGetEmailServiceConfigOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.NewbillingGetEmailServiceConfigResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewNotifierGetEmailServiceConfigDefault creates a NotifierGetEmailServiceConfigDefault with default headers values
func NewNotifierGetEmailServiceConfigDefault(code int) *NotifierGetEmailServiceConfigDefault {
	return &NotifierGetEmailServiceConfigDefault{
		_statusCode: code,
	}
}

/*
NotifierGetEmailServiceConfigDefault describes a response with status code -1, with default header values.

An unexpected error response
*/
type NotifierGetEmailServiceConfigDefault struct {
	_statusCode int

	Payload *models.RuntimeError
}

// Code gets the status code for the notifier get email service config default response
func (o *NotifierGetEmailServiceConfigDefault) Code() int {
	return o._statusCode
}

// IsSuccess returns true when this notifier get email service config default response has a 2xx status code
func (o *NotifierGetEmailServiceConfigDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this notifier get email service config default response has a 3xx status code
func (o *NotifierGetEmailServiceConfigDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this notifier get email service config default response has a 4xx status code
func (o *NotifierGetEmailServiceConfigDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this notifier get email service config default response has a 5xx status code
func (o *NotifierGetEmailServiceConfigDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this notifier get email service config default response a status code equal to that given
func (o *NotifierGetEmailServiceConfigDefault) IsCode(code int) bool {
	return o._statusCode == code
}

func (o *NotifierGetEmailServiceConfigDefault) Error() string {
	return fmt.Sprintf("[GET /v1/emailserviceconfig][%d] Notifier_GetEmailServiceConfig default  %+v", o._statusCode, o.Payload)
}

func (o *NotifierGetEmailServiceConfigDefault) String() string {
	return fmt.Sprintf("[GET /v1/emailserviceconfig][%d] Notifier_GetEmailServiceConfig default  %+v", o._statusCode, o.Payload)
}

func (o *NotifierGetEmailServiceConfigDefault) GetPayload() *models.RuntimeError {
	return o.Payload
}

func (o *NotifierGetEmailServiceConfigDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RuntimeError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
