// Code generated by go-swagger; DO NOT EDIT.

package collect_manager

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/KubeSphereCloud/newbilling-client-go/models"
)

// NewCollectManagerStopCollectParams creates a new CollectManagerStopCollectParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCollectManagerStopCollectParams() *CollectManagerStopCollectParams {
	return &CollectManagerStopCollectParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCollectManagerStopCollectParamsWithTimeout creates a new CollectManagerStopCollectParams object
// with the ability to set a timeout on a request.
func NewCollectManagerStopCollectParamsWithTimeout(timeout time.Duration) *CollectManagerStopCollectParams {
	return &CollectManagerStopCollectParams{
		timeout: timeout,
	}
}

// NewCollectManagerStopCollectParamsWithContext creates a new CollectManagerStopCollectParams object
// with the ability to set a context for a request.
func NewCollectManagerStopCollectParamsWithContext(ctx context.Context) *CollectManagerStopCollectParams {
	return &CollectManagerStopCollectParams{
		Context: ctx,
	}
}

// NewCollectManagerStopCollectParamsWithHTTPClient creates a new CollectManagerStopCollectParams object
// with the ability to set a custom HTTPClient for a request.
func NewCollectManagerStopCollectParamsWithHTTPClient(client *http.Client) *CollectManagerStopCollectParams {
	return &CollectManagerStopCollectParams{
		HTTPClient: client,
	}
}

/*
CollectManagerStopCollectParams contains all the parameters to send to the API endpoint

	for the collect manager stop collect operation.

	Typically these are written to a http.Request.
*/
type CollectManagerStopCollectParams struct {

	// Body.
	Body *models.NewbillingStopCollectRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the collect manager stop collect params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CollectManagerStopCollectParams) WithDefaults() *CollectManagerStopCollectParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the collect manager stop collect params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CollectManagerStopCollectParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the collect manager stop collect params
func (o *CollectManagerStopCollectParams) WithTimeout(timeout time.Duration) *CollectManagerStopCollectParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the collect manager stop collect params
func (o *CollectManagerStopCollectParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the collect manager stop collect params
func (o *CollectManagerStopCollectParams) WithContext(ctx context.Context) *CollectManagerStopCollectParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the collect manager stop collect params
func (o *CollectManagerStopCollectParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the collect manager stop collect params
func (o *CollectManagerStopCollectParams) WithHTTPClient(client *http.Client) *CollectManagerStopCollectParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the collect manager stop collect params
func (o *CollectManagerStopCollectParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the collect manager stop collect params
func (o *CollectManagerStopCollectParams) WithBody(body *models.NewbillingStopCollectRequest) *CollectManagerStopCollectParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the collect manager stop collect params
func (o *CollectManagerStopCollectParams) SetBody(body *models.NewbillingStopCollectRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *CollectManagerStopCollectParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
