// Code generated by go-swagger; DO NOT EDIT.

package pricing_manager

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/KubeSphereCloud/newbilling-client-go/models"
)

// PricingManagerDescribePublicAttributesReader is a Reader for the PricingManagerDescribePublicAttributes structure.
type PricingManagerDescribePublicAttributesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PricingManagerDescribePublicAttributesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPricingManagerDescribePublicAttributesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewPricingManagerDescribePublicAttributesDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewPricingManagerDescribePublicAttributesOK creates a PricingManagerDescribePublicAttributesOK with default headers values
func NewPricingManagerDescribePublicAttributesOK() *PricingManagerDescribePublicAttributesOK {
	return &PricingManagerDescribePublicAttributesOK{}
}

/*
PricingManagerDescribePublicAttributesOK describes a response with status code 200, with default header values.

A successful response.
*/
type PricingManagerDescribePublicAttributesOK struct {
	Payload *models.NewbillingDescribePublicAttributesResponse
}

// IsSuccess returns true when this pricing manager describe public attributes o k response has a 2xx status code
func (o *PricingManagerDescribePublicAttributesOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this pricing manager describe public attributes o k response has a 3xx status code
func (o *PricingManagerDescribePublicAttributesOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this pricing manager describe public attributes o k response has a 4xx status code
func (o *PricingManagerDescribePublicAttributesOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this pricing manager describe public attributes o k response has a 5xx status code
func (o *PricingManagerDescribePublicAttributesOK) IsServerError() bool {
	return false
}

// IsCode returns true when this pricing manager describe public attributes o k response a status code equal to that given
func (o *PricingManagerDescribePublicAttributesOK) IsCode(code int) bool {
	return code == 200
}

func (o *PricingManagerDescribePublicAttributesOK) Error() string {
	return fmt.Sprintf("[GET /v1/publicattrs][%d] pricingManagerDescribePublicAttributesOK  %+v", 200, o.Payload)
}

func (o *PricingManagerDescribePublicAttributesOK) String() string {
	return fmt.Sprintf("[GET /v1/publicattrs][%d] pricingManagerDescribePublicAttributesOK  %+v", 200, o.Payload)
}

func (o *PricingManagerDescribePublicAttributesOK) GetPayload() *models.NewbillingDescribePublicAttributesResponse {
	return o.Payload
}

func (o *PricingManagerDescribePublicAttributesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.NewbillingDescribePublicAttributesResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPricingManagerDescribePublicAttributesDefault creates a PricingManagerDescribePublicAttributesDefault with default headers values
func NewPricingManagerDescribePublicAttributesDefault(code int) *PricingManagerDescribePublicAttributesDefault {
	return &PricingManagerDescribePublicAttributesDefault{
		_statusCode: code,
	}
}

/*
PricingManagerDescribePublicAttributesDefault describes a response with status code -1, with default header values.

An unexpected error response
*/
type PricingManagerDescribePublicAttributesDefault struct {
	_statusCode int

	Payload *models.RuntimeError
}

// Code gets the status code for the pricing manager describe public attributes default response
func (o *PricingManagerDescribePublicAttributesDefault) Code() int {
	return o._statusCode
}

// IsSuccess returns true when this pricing manager describe public attributes default response has a 2xx status code
func (o *PricingManagerDescribePublicAttributesDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this pricing manager describe public attributes default response has a 3xx status code
func (o *PricingManagerDescribePublicAttributesDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this pricing manager describe public attributes default response has a 4xx status code
func (o *PricingManagerDescribePublicAttributesDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this pricing manager describe public attributes default response has a 5xx status code
func (o *PricingManagerDescribePublicAttributesDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this pricing manager describe public attributes default response a status code equal to that given
func (o *PricingManagerDescribePublicAttributesDefault) IsCode(code int) bool {
	return o._statusCode == code
}

func (o *PricingManagerDescribePublicAttributesDefault) Error() string {
	return fmt.Sprintf("[GET /v1/publicattrs][%d] PricingManager_DescribePublicAttributes default  %+v", o._statusCode, o.Payload)
}

func (o *PricingManagerDescribePublicAttributesDefault) String() string {
	return fmt.Sprintf("[GET /v1/publicattrs][%d] PricingManager_DescribePublicAttributes default  %+v", o._statusCode, o.Payload)
}

func (o *PricingManagerDescribePublicAttributesDefault) GetPayload() *models.RuntimeError {
	return o.Payload
}

func (o *PricingManagerDescribePublicAttributesDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RuntimeError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
