// Code generated by go-swagger; DO NOT EDIT.

package pricing_manager

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/KubeSphereCloud/newbilling-client-go/models"
)

// PricingManagerUnMappingComponentReader is a Reader for the PricingManagerUnMappingComponent structure.
type PricingManagerUnMappingComponentReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PricingManagerUnMappingComponentReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPricingManagerUnMappingComponentOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewPricingManagerUnMappingComponentDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewPricingManagerUnMappingComponentOK creates a PricingManagerUnMappingComponentOK with default headers values
func NewPricingManagerUnMappingComponentOK() *PricingManagerUnMappingComponentOK {
	return &PricingManagerUnMappingComponentOK{}
}

/*
PricingManagerUnMappingComponentOK describes a response with status code 200, with default header values.

A successful response.
*/
type PricingManagerUnMappingComponentOK struct {
	Payload *models.NewbillingUnMappingComponentResponse
}

// IsSuccess returns true when this pricing manager un mapping component o k response has a 2xx status code
func (o *PricingManagerUnMappingComponentOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this pricing manager un mapping component o k response has a 3xx status code
func (o *PricingManagerUnMappingComponentOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this pricing manager un mapping component o k response has a 4xx status code
func (o *PricingManagerUnMappingComponentOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this pricing manager un mapping component o k response has a 5xx status code
func (o *PricingManagerUnMappingComponentOK) IsServerError() bool {
	return false
}

// IsCode returns true when this pricing manager un mapping component o k response a status code equal to that given
func (o *PricingManagerUnMappingComponentOK) IsCode(code int) bool {
	return code == 200
}

func (o *PricingManagerUnMappingComponentOK) Error() string {
	return fmt.Sprintf("[POST /v1/components:canceltransfer][%d] pricingManagerUnMappingComponentOK  %+v", 200, o.Payload)
}

func (o *PricingManagerUnMappingComponentOK) String() string {
	return fmt.Sprintf("[POST /v1/components:canceltransfer][%d] pricingManagerUnMappingComponentOK  %+v", 200, o.Payload)
}

func (o *PricingManagerUnMappingComponentOK) GetPayload() *models.NewbillingUnMappingComponentResponse {
	return o.Payload
}

func (o *PricingManagerUnMappingComponentOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.NewbillingUnMappingComponentResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPricingManagerUnMappingComponentDefault creates a PricingManagerUnMappingComponentDefault with default headers values
func NewPricingManagerUnMappingComponentDefault(code int) *PricingManagerUnMappingComponentDefault {
	return &PricingManagerUnMappingComponentDefault{
		_statusCode: code,
	}
}

/*
PricingManagerUnMappingComponentDefault describes a response with status code -1, with default header values.

An unexpected error response
*/
type PricingManagerUnMappingComponentDefault struct {
	_statusCode int

	Payload *models.RuntimeError
}

// Code gets the status code for the pricing manager un mapping component default response
func (o *PricingManagerUnMappingComponentDefault) Code() int {
	return o._statusCode
}

// IsSuccess returns true when this pricing manager un mapping component default response has a 2xx status code
func (o *PricingManagerUnMappingComponentDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this pricing manager un mapping component default response has a 3xx status code
func (o *PricingManagerUnMappingComponentDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this pricing manager un mapping component default response has a 4xx status code
func (o *PricingManagerUnMappingComponentDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this pricing manager un mapping component default response has a 5xx status code
func (o *PricingManagerUnMappingComponentDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this pricing manager un mapping component default response a status code equal to that given
func (o *PricingManagerUnMappingComponentDefault) IsCode(code int) bool {
	return o._statusCode == code
}

func (o *PricingManagerUnMappingComponentDefault) Error() string {
	return fmt.Sprintf("[POST /v1/components:canceltransfer][%d] PricingManager_UnMappingComponent default  %+v", o._statusCode, o.Payload)
}

func (o *PricingManagerUnMappingComponentDefault) String() string {
	return fmt.Sprintf("[POST /v1/components:canceltransfer][%d] PricingManager_UnMappingComponent default  %+v", o._statusCode, o.Payload)
}

func (o *PricingManagerUnMappingComponentDefault) GetPayload() *models.RuntimeError {
	return o.Payload
}

func (o *PricingManagerUnMappingComponentDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RuntimeError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
