// Code generated by go-swagger; DO NOT EDIT.

package pricing_manager

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/KubeSphereCloud/newbilling-client-go/models"
)

// PricingManagerGetPricingReader is a Reader for the PricingManagerGetPricing structure.
type PricingManagerGetPricingReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PricingManagerGetPricingReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPricingManagerGetPricingOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewPricingManagerGetPricingDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewPricingManagerGetPricingOK creates a PricingManagerGetPricingOK with default headers values
func NewPricingManagerGetPricingOK() *PricingManagerGetPricingOK {
	return &PricingManagerGetPricingOK{}
}

/*
PricingManagerGetPricingOK describes a response with status code 200, with default header values.

A successful response.
*/
type PricingManagerGetPricingOK struct {
	Payload *models.NewbillingGetPricingResponse
}

// IsSuccess returns true when this pricing manager get pricing o k response has a 2xx status code
func (o *PricingManagerGetPricingOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this pricing manager get pricing o k response has a 3xx status code
func (o *PricingManagerGetPricingOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this pricing manager get pricing o k response has a 4xx status code
func (o *PricingManagerGetPricingOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this pricing manager get pricing o k response has a 5xx status code
func (o *PricingManagerGetPricingOK) IsServerError() bool {
	return false
}

// IsCode returns true when this pricing manager get pricing o k response a status code equal to that given
func (o *PricingManagerGetPricingOK) IsCode(code int) bool {
	return code == 200
}

func (o *PricingManagerGetPricingOK) Error() string {
	return fmt.Sprintf("[GET /v1/pricing][%d] pricingManagerGetPricingOK  %+v", 200, o.Payload)
}

func (o *PricingManagerGetPricingOK) String() string {
	return fmt.Sprintf("[GET /v1/pricing][%d] pricingManagerGetPricingOK  %+v", 200, o.Payload)
}

func (o *PricingManagerGetPricingOK) GetPayload() *models.NewbillingGetPricingResponse {
	return o.Payload
}

func (o *PricingManagerGetPricingOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.NewbillingGetPricingResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPricingManagerGetPricingDefault creates a PricingManagerGetPricingDefault with default headers values
func NewPricingManagerGetPricingDefault(code int) *PricingManagerGetPricingDefault {
	return &PricingManagerGetPricingDefault{
		_statusCode: code,
	}
}

/*
PricingManagerGetPricingDefault describes a response with status code -1, with default header values.

An unexpected error response
*/
type PricingManagerGetPricingDefault struct {
	_statusCode int

	Payload *models.RuntimeError
}

// Code gets the status code for the pricing manager get pricing default response
func (o *PricingManagerGetPricingDefault) Code() int {
	return o._statusCode
}

// IsSuccess returns true when this pricing manager get pricing default response has a 2xx status code
func (o *PricingManagerGetPricingDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this pricing manager get pricing default response has a 3xx status code
func (o *PricingManagerGetPricingDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this pricing manager get pricing default response has a 4xx status code
func (o *PricingManagerGetPricingDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this pricing manager get pricing default response has a 5xx status code
func (o *PricingManagerGetPricingDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this pricing manager get pricing default response a status code equal to that given
func (o *PricingManagerGetPricingDefault) IsCode(code int) bool {
	return o._statusCode == code
}

func (o *PricingManagerGetPricingDefault) Error() string {
	return fmt.Sprintf("[GET /v1/pricing][%d] PricingManager_GetPricing default  %+v", o._statusCode, o.Payload)
}

func (o *PricingManagerGetPricingDefault) String() string {
	return fmt.Sprintf("[GET /v1/pricing][%d] PricingManager_GetPricing default  %+v", o._statusCode, o.Payload)
}

func (o *PricingManagerGetPricingDefault) GetPayload() *models.RuntimeError {
	return o.Payload
}

func (o *PricingManagerGetPricingDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RuntimeError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
