// Code generated by go-swagger; DO NOT EDIT.

package pricing_manager

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/KubeSphereCloud/newbilling-client-go/models"
)

// NewPricingManagerMappingComponentParams creates a new PricingManagerMappingComponentParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPricingManagerMappingComponentParams() *PricingManagerMappingComponentParams {
	return &PricingManagerMappingComponentParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPricingManagerMappingComponentParamsWithTimeout creates a new PricingManagerMappingComponentParams object
// with the ability to set a timeout on a request.
func NewPricingManagerMappingComponentParamsWithTimeout(timeout time.Duration) *PricingManagerMappingComponentParams {
	return &PricingManagerMappingComponentParams{
		timeout: timeout,
	}
}

// NewPricingManagerMappingComponentParamsWithContext creates a new PricingManagerMappingComponentParams object
// with the ability to set a context for a request.
func NewPricingManagerMappingComponentParamsWithContext(ctx context.Context) *PricingManagerMappingComponentParams {
	return &PricingManagerMappingComponentParams{
		Context: ctx,
	}
}

// NewPricingManagerMappingComponentParamsWithHTTPClient creates a new PricingManagerMappingComponentParams object
// with the ability to set a custom HTTPClient for a request.
func NewPricingManagerMappingComponentParamsWithHTTPClient(client *http.Client) *PricingManagerMappingComponentParams {
	return &PricingManagerMappingComponentParams{
		HTTPClient: client,
	}
}

/*
PricingManagerMappingComponentParams contains all the parameters to send to the API endpoint

	for the pricing manager mapping component operation.

	Typically these are written to a http.Request.
*/
type PricingManagerMappingComponentParams struct {

	// Body.
	Body *models.NewbillingMappingComponentRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the pricing manager mapping component params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PricingManagerMappingComponentParams) WithDefaults() *PricingManagerMappingComponentParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the pricing manager mapping component params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PricingManagerMappingComponentParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the pricing manager mapping component params
func (o *PricingManagerMappingComponentParams) WithTimeout(timeout time.Duration) *PricingManagerMappingComponentParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the pricing manager mapping component params
func (o *PricingManagerMappingComponentParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the pricing manager mapping component params
func (o *PricingManagerMappingComponentParams) WithContext(ctx context.Context) *PricingManagerMappingComponentParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the pricing manager mapping component params
func (o *PricingManagerMappingComponentParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the pricing manager mapping component params
func (o *PricingManagerMappingComponentParams) WithHTTPClient(client *http.Client) *PricingManagerMappingComponentParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the pricing manager mapping component params
func (o *PricingManagerMappingComponentParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the pricing manager mapping component params
func (o *PricingManagerMappingComponentParams) WithBody(body *models.NewbillingMappingComponentRequest) *PricingManagerMappingComponentParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the pricing manager mapping component params
func (o *PricingManagerMappingComponentParams) SetBody(body *models.NewbillingMappingComponentRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *PricingManagerMappingComponentParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
