// Code generated by go-swagger; DO NOT EDIT.

package pricing_manager

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/KubeSphereCloud/newbilling-client-go/models"
)

// NewPricingManagerDeleteComponentsParams creates a new PricingManagerDeleteComponentsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPricingManagerDeleteComponentsParams() *PricingManagerDeleteComponentsParams {
	return &PricingManagerDeleteComponentsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPricingManagerDeleteComponentsParamsWithTimeout creates a new PricingManagerDeleteComponentsParams object
// with the ability to set a timeout on a request.
func NewPricingManagerDeleteComponentsParamsWithTimeout(timeout time.Duration) *PricingManagerDeleteComponentsParams {
	return &PricingManagerDeleteComponentsParams{
		timeout: timeout,
	}
}

// NewPricingManagerDeleteComponentsParamsWithContext creates a new PricingManagerDeleteComponentsParams object
// with the ability to set a context for a request.
func NewPricingManagerDeleteComponentsParamsWithContext(ctx context.Context) *PricingManagerDeleteComponentsParams {
	return &PricingManagerDeleteComponentsParams{
		Context: ctx,
	}
}

// NewPricingManagerDeleteComponentsParamsWithHTTPClient creates a new PricingManagerDeleteComponentsParams object
// with the ability to set a custom HTTPClient for a request.
func NewPricingManagerDeleteComponentsParamsWithHTTPClient(client *http.Client) *PricingManagerDeleteComponentsParams {
	return &PricingManagerDeleteComponentsParams{
		HTTPClient: client,
	}
}

/*
PricingManagerDeleteComponentsParams contains all the parameters to send to the API endpoint

	for the pricing manager delete components operation.

	Typically these are written to a http.Request.
*/
type PricingManagerDeleteComponentsParams struct {

	// Body.
	Body *models.NewbillingDeleteComponentsRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the pricing manager delete components params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PricingManagerDeleteComponentsParams) WithDefaults() *PricingManagerDeleteComponentsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the pricing manager delete components params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PricingManagerDeleteComponentsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the pricing manager delete components params
func (o *PricingManagerDeleteComponentsParams) WithTimeout(timeout time.Duration) *PricingManagerDeleteComponentsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the pricing manager delete components params
func (o *PricingManagerDeleteComponentsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the pricing manager delete components params
func (o *PricingManagerDeleteComponentsParams) WithContext(ctx context.Context) *PricingManagerDeleteComponentsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the pricing manager delete components params
func (o *PricingManagerDeleteComponentsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the pricing manager delete components params
func (o *PricingManagerDeleteComponentsParams) WithHTTPClient(client *http.Client) *PricingManagerDeleteComponentsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the pricing manager delete components params
func (o *PricingManagerDeleteComponentsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the pricing manager delete components params
func (o *PricingManagerDeleteComponentsParams) WithBody(body *models.NewbillingDeleteComponentsRequest) *PricingManagerDeleteComponentsParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the pricing manager delete components params
func (o *PricingManagerDeleteComponentsParams) SetBody(body *models.NewbillingDeleteComponentsRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *PricingManagerDeleteComponentsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
