// Code generated by go-swagger; DO NOT EDIT.

package pricing_manager

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/KubeSphereCloud/newbilling-client-go/models"
)

// PricingManagerCreateComponentOfResPkgReader is a Reader for the PricingManagerCreateComponentOfResPkg structure.
type PricingManagerCreateComponentOfResPkgReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PricingManagerCreateComponentOfResPkgReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPricingManagerCreateComponentOfResPkgOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewPricingManagerCreateComponentOfResPkgDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewPricingManagerCreateComponentOfResPkgOK creates a PricingManagerCreateComponentOfResPkgOK with default headers values
func NewPricingManagerCreateComponentOfResPkgOK() *PricingManagerCreateComponentOfResPkgOK {
	return &PricingManagerCreateComponentOfResPkgOK{}
}

/*
PricingManagerCreateComponentOfResPkgOK describes a response with status code 200, with default header values.

A successful response.
*/
type PricingManagerCreateComponentOfResPkgOK struct {
	Payload *models.NewbillingComponentOfPricingSimpleResponse
}

// IsSuccess returns true when this pricing manager create component of res pkg o k response has a 2xx status code
func (o *PricingManagerCreateComponentOfResPkgOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this pricing manager create component of res pkg o k response has a 3xx status code
func (o *PricingManagerCreateComponentOfResPkgOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this pricing manager create component of res pkg o k response has a 4xx status code
func (o *PricingManagerCreateComponentOfResPkgOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this pricing manager create component of res pkg o k response has a 5xx status code
func (o *PricingManagerCreateComponentOfResPkgOK) IsServerError() bool {
	return false
}

// IsCode returns true when this pricing manager create component of res pkg o k response a status code equal to that given
func (o *PricingManagerCreateComponentOfResPkgOK) IsCode(code int) bool {
	return code == 200
}

func (o *PricingManagerCreateComponentOfResPkgOK) Error() string {
	return fmt.Sprintf("[POST /v1/componentsofrespkg][%d] pricingManagerCreateComponentOfResPkgOK  %+v", 200, o.Payload)
}

func (o *PricingManagerCreateComponentOfResPkgOK) String() string {
	return fmt.Sprintf("[POST /v1/componentsofrespkg][%d] pricingManagerCreateComponentOfResPkgOK  %+v", 200, o.Payload)
}

func (o *PricingManagerCreateComponentOfResPkgOK) GetPayload() *models.NewbillingComponentOfPricingSimpleResponse {
	return o.Payload
}

func (o *PricingManagerCreateComponentOfResPkgOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.NewbillingComponentOfPricingSimpleResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPricingManagerCreateComponentOfResPkgDefault creates a PricingManagerCreateComponentOfResPkgDefault with default headers values
func NewPricingManagerCreateComponentOfResPkgDefault(code int) *PricingManagerCreateComponentOfResPkgDefault {
	return &PricingManagerCreateComponentOfResPkgDefault{
		_statusCode: code,
	}
}

/*
PricingManagerCreateComponentOfResPkgDefault describes a response with status code -1, with default header values.

An unexpected error response
*/
type PricingManagerCreateComponentOfResPkgDefault struct {
	_statusCode int

	Payload *models.RuntimeError
}

// Code gets the status code for the pricing manager create component of res pkg default response
func (o *PricingManagerCreateComponentOfResPkgDefault) Code() int {
	return o._statusCode
}

// IsSuccess returns true when this pricing manager create component of res pkg default response has a 2xx status code
func (o *PricingManagerCreateComponentOfResPkgDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this pricing manager create component of res pkg default response has a 3xx status code
func (o *PricingManagerCreateComponentOfResPkgDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this pricing manager create component of res pkg default response has a 4xx status code
func (o *PricingManagerCreateComponentOfResPkgDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this pricing manager create component of res pkg default response has a 5xx status code
func (o *PricingManagerCreateComponentOfResPkgDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this pricing manager create component of res pkg default response a status code equal to that given
func (o *PricingManagerCreateComponentOfResPkgDefault) IsCode(code int) bool {
	return o._statusCode == code
}

func (o *PricingManagerCreateComponentOfResPkgDefault) Error() string {
	return fmt.Sprintf("[POST /v1/componentsofrespkg][%d] PricingManager_CreateComponentOfResPkg default  %+v", o._statusCode, o.Payload)
}

func (o *PricingManagerCreateComponentOfResPkgDefault) String() string {
	return fmt.Sprintf("[POST /v1/componentsofrespkg][%d] PricingManager_CreateComponentOfResPkg default  %+v", o._statusCode, o.Payload)
}

func (o *PricingManagerCreateComponentOfResPkgDefault) GetPayload() *models.RuntimeError {
	return o.Payload
}

func (o *PricingManagerCreateComponentOfResPkgDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RuntimeError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
