// Code generated by go-swagger; DO NOT EDIT.

package payment

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPaymentGetOrderParams creates a new PaymentGetOrderParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPaymentGetOrderParams() *PaymentGetOrderParams {
	return &PaymentGetOrderParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPaymentGetOrderParamsWithTimeout creates a new PaymentGetOrderParams object
// with the ability to set a timeout on a request.
func NewPaymentGetOrderParamsWithTimeout(timeout time.Duration) *PaymentGetOrderParams {
	return &PaymentGetOrderParams{
		timeout: timeout,
	}
}

// NewPaymentGetOrderParamsWithContext creates a new PaymentGetOrderParams object
// with the ability to set a context for a request.
func NewPaymentGetOrderParamsWithContext(ctx context.Context) *PaymentGetOrderParams {
	return &PaymentGetOrderParams{
		Context: ctx,
	}
}

// NewPaymentGetOrderParamsWithHTTPClient creates a new PaymentGetOrderParams object
// with the ability to set a custom HTTPClient for a request.
func NewPaymentGetOrderParamsWithHTTPClient(client *http.Client) *PaymentGetOrderParams {
	return &PaymentGetOrderParams{
		HTTPClient: client,
	}
}

/*
PaymentGetOrderParams contains all the parameters to send to the API endpoint

	for the payment get order operation.

	Typically these are written to a http.Request.
*/
type PaymentGetOrderParams struct {

	// AccessSysID.
	AccessSysID *string

	// QueryNo.
	QueryNo string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the payment get order params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PaymentGetOrderParams) WithDefaults() *PaymentGetOrderParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the payment get order params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PaymentGetOrderParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the payment get order params
func (o *PaymentGetOrderParams) WithTimeout(timeout time.Duration) *PaymentGetOrderParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the payment get order params
func (o *PaymentGetOrderParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the payment get order params
func (o *PaymentGetOrderParams) WithContext(ctx context.Context) *PaymentGetOrderParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the payment get order params
func (o *PaymentGetOrderParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the payment get order params
func (o *PaymentGetOrderParams) WithHTTPClient(client *http.Client) *PaymentGetOrderParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the payment get order params
func (o *PaymentGetOrderParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAccessSysID adds the accessSysID to the payment get order params
func (o *PaymentGetOrderParams) WithAccessSysID(accessSysID *string) *PaymentGetOrderParams {
	o.SetAccessSysID(accessSysID)
	return o
}

// SetAccessSysID adds the accessSysId to the payment get order params
func (o *PaymentGetOrderParams) SetAccessSysID(accessSysID *string) {
	o.AccessSysID = accessSysID
}

// WithQueryNo adds the queryNo to the payment get order params
func (o *PaymentGetOrderParams) WithQueryNo(queryNo string) *PaymentGetOrderParams {
	o.SetQueryNo(queryNo)
	return o
}

// SetQueryNo adds the queryNo to the payment get order params
func (o *PaymentGetOrderParams) SetQueryNo(queryNo string) {
	o.QueryNo = queryNo
}

// WriteToRequest writes these params to a swagger request
func (o *PaymentGetOrderParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.AccessSysID != nil {

		// query param access_sys_id
		var qrAccessSysID string

		if o.AccessSysID != nil {
			qrAccessSysID = *o.AccessSysID
		}
		qAccessSysID := qrAccessSysID
		if qAccessSysID != "" {

			if err := r.SetQueryParam("access_sys_id", qAccessSysID); err != nil {
				return err
			}
		}
	}

	// path param query_no
	if err := r.SetPathParam("query_no", o.QueryNo); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
