// Code generated by go-swagger; DO NOT EDIT.

package payment

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/KubeSphereCloud/newbilling-client-go/models"
)

// PaymentPrepayStripeReader is a Reader for the PaymentPrepayStripe structure.
type PaymentPrepayStripeReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PaymentPrepayStripeReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPaymentPrepayStripeOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewPaymentPrepayStripeDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewPaymentPrepayStripeOK creates a PaymentPrepayStripeOK with default headers values
func NewPaymentPrepayStripeOK() *PaymentPrepayStripeOK {
	return &PaymentPrepayStripeOK{}
}

/*
PaymentPrepayStripeOK describes a response with status code 200, with default header values.

A successful response.
*/
type PaymentPrepayStripeOK struct {
	Payload *models.NewbillingPrepayStripeResponse
}

// IsSuccess returns true when this payment prepay stripe o k response has a 2xx status code
func (o *PaymentPrepayStripeOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this payment prepay stripe o k response has a 3xx status code
func (o *PaymentPrepayStripeOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this payment prepay stripe o k response has a 4xx status code
func (o *PaymentPrepayStripeOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this payment prepay stripe o k response has a 5xx status code
func (o *PaymentPrepayStripeOK) IsServerError() bool {
	return false
}

// IsCode returns true when this payment prepay stripe o k response a status code equal to that given
func (o *PaymentPrepayStripeOK) IsCode(code int) bool {
	return code == 200
}

func (o *PaymentPrepayStripeOK) Error() string {
	return fmt.Sprintf("[POST /v1/prepay/stripe][%d] paymentPrepayStripeOK  %+v", 200, o.Payload)
}

func (o *PaymentPrepayStripeOK) String() string {
	return fmt.Sprintf("[POST /v1/prepay/stripe][%d] paymentPrepayStripeOK  %+v", 200, o.Payload)
}

func (o *PaymentPrepayStripeOK) GetPayload() *models.NewbillingPrepayStripeResponse {
	return o.Payload
}

func (o *PaymentPrepayStripeOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.NewbillingPrepayStripeResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPaymentPrepayStripeDefault creates a PaymentPrepayStripeDefault with default headers values
func NewPaymentPrepayStripeDefault(code int) *PaymentPrepayStripeDefault {
	return &PaymentPrepayStripeDefault{
		_statusCode: code,
	}
}

/*
PaymentPrepayStripeDefault describes a response with status code -1, with default header values.

An unexpected error response
*/
type PaymentPrepayStripeDefault struct {
	_statusCode int

	Payload *models.RuntimeError
}

// Code gets the status code for the payment prepay stripe default response
func (o *PaymentPrepayStripeDefault) Code() int {
	return o._statusCode
}

// IsSuccess returns true when this payment prepay stripe default response has a 2xx status code
func (o *PaymentPrepayStripeDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this payment prepay stripe default response has a 3xx status code
func (o *PaymentPrepayStripeDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this payment prepay stripe default response has a 4xx status code
func (o *PaymentPrepayStripeDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this payment prepay stripe default response has a 5xx status code
func (o *PaymentPrepayStripeDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this payment prepay stripe default response a status code equal to that given
func (o *PaymentPrepayStripeDefault) IsCode(code int) bool {
	return o._statusCode == code
}

func (o *PaymentPrepayStripeDefault) Error() string {
	return fmt.Sprintf("[POST /v1/prepay/stripe][%d] Payment_PrepayStripe default  %+v", o._statusCode, o.Payload)
}

func (o *PaymentPrepayStripeDefault) String() string {
	return fmt.Sprintf("[POST /v1/prepay/stripe][%d] Payment_PrepayStripe default  %+v", o._statusCode, o.Payload)
}

func (o *PaymentPrepayStripeDefault) GetPayload() *models.RuntimeError {
	return o.Payload
}

func (o *PaymentPrepayStripeDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RuntimeError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
