// Code generated by go-swagger; DO NOT EDIT.

package subscription_prod_instance_manager

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/KubeSphereCloud/newbilling-client-go/models"
)

// NewSubscriptionProdInstanceManagerStopProdInstanceParams creates a new SubscriptionProdInstanceManagerStopProdInstanceParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewSubscriptionProdInstanceManagerStopProdInstanceParams() *SubscriptionProdInstanceManagerStopProdInstanceParams {
	return &SubscriptionProdInstanceManagerStopProdInstanceParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewSubscriptionProdInstanceManagerStopProdInstanceParamsWithTimeout creates a new SubscriptionProdInstanceManagerStopProdInstanceParams object
// with the ability to set a timeout on a request.
func NewSubscriptionProdInstanceManagerStopProdInstanceParamsWithTimeout(timeout time.Duration) *SubscriptionProdInstanceManagerStopProdInstanceParams {
	return &SubscriptionProdInstanceManagerStopProdInstanceParams{
		timeout: timeout,
	}
}

// NewSubscriptionProdInstanceManagerStopProdInstanceParamsWithContext creates a new SubscriptionProdInstanceManagerStopProdInstanceParams object
// with the ability to set a context for a request.
func NewSubscriptionProdInstanceManagerStopProdInstanceParamsWithContext(ctx context.Context) *SubscriptionProdInstanceManagerStopProdInstanceParams {
	return &SubscriptionProdInstanceManagerStopProdInstanceParams{
		Context: ctx,
	}
}

// NewSubscriptionProdInstanceManagerStopProdInstanceParamsWithHTTPClient creates a new SubscriptionProdInstanceManagerStopProdInstanceParams object
// with the ability to set a custom HTTPClient for a request.
func NewSubscriptionProdInstanceManagerStopProdInstanceParamsWithHTTPClient(client *http.Client) *SubscriptionProdInstanceManagerStopProdInstanceParams {
	return &SubscriptionProdInstanceManagerStopProdInstanceParams{
		HTTPClient: client,
	}
}

/*
SubscriptionProdInstanceManagerStopProdInstanceParams contains all the parameters to send to the API endpoint

	for the subscription prod instance manager stop prod instance operation.

	Typically these are written to a http.Request.
*/
type SubscriptionProdInstanceManagerStopProdInstanceParams struct {

	// Body.
	Body *models.NewbillingStopProdInstanceRequest

	/* ProdInstIDExt.

	   产品实例ID
	*/
	ProdInstIDExt string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the subscription prod instance manager stop prod instance params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SubscriptionProdInstanceManagerStopProdInstanceParams) WithDefaults() *SubscriptionProdInstanceManagerStopProdInstanceParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the subscription prod instance manager stop prod instance params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SubscriptionProdInstanceManagerStopProdInstanceParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the subscription prod instance manager stop prod instance params
func (o *SubscriptionProdInstanceManagerStopProdInstanceParams) WithTimeout(timeout time.Duration) *SubscriptionProdInstanceManagerStopProdInstanceParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the subscription prod instance manager stop prod instance params
func (o *SubscriptionProdInstanceManagerStopProdInstanceParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the subscription prod instance manager stop prod instance params
func (o *SubscriptionProdInstanceManagerStopProdInstanceParams) WithContext(ctx context.Context) *SubscriptionProdInstanceManagerStopProdInstanceParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the subscription prod instance manager stop prod instance params
func (o *SubscriptionProdInstanceManagerStopProdInstanceParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the subscription prod instance manager stop prod instance params
func (o *SubscriptionProdInstanceManagerStopProdInstanceParams) WithHTTPClient(client *http.Client) *SubscriptionProdInstanceManagerStopProdInstanceParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the subscription prod instance manager stop prod instance params
func (o *SubscriptionProdInstanceManagerStopProdInstanceParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the subscription prod instance manager stop prod instance params
func (o *SubscriptionProdInstanceManagerStopProdInstanceParams) WithBody(body *models.NewbillingStopProdInstanceRequest) *SubscriptionProdInstanceManagerStopProdInstanceParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the subscription prod instance manager stop prod instance params
func (o *SubscriptionProdInstanceManagerStopProdInstanceParams) SetBody(body *models.NewbillingStopProdInstanceRequest) {
	o.Body = body
}

// WithProdInstIDExt adds the prodInstIDExt to the subscription prod instance manager stop prod instance params
func (o *SubscriptionProdInstanceManagerStopProdInstanceParams) WithProdInstIDExt(prodInstIDExt string) *SubscriptionProdInstanceManagerStopProdInstanceParams {
	o.SetProdInstIDExt(prodInstIDExt)
	return o
}

// SetProdInstIDExt adds the prodInstIdExt to the subscription prod instance manager stop prod instance params
func (o *SubscriptionProdInstanceManagerStopProdInstanceParams) SetProdInstIDExt(prodInstIDExt string) {
	o.ProdInstIDExt = prodInstIDExt
}

// WriteToRequest writes these params to a swagger request
func (o *SubscriptionProdInstanceManagerStopProdInstanceParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param prod_inst_id_ext
	if err := r.SetPathParam("prod_inst_id_ext", o.ProdInstIDExt); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
