// Code generated by go-swagger; DO NOT EDIT.

package iam_manager

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/KubeSphereCloud/newbilling-client-go/models"
)

// NewIamManagerChangePasswordParams creates a new IamManagerChangePasswordParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewIamManagerChangePasswordParams() *IamManagerChangePasswordParams {
	return &IamManagerChangePasswordParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewIamManagerChangePasswordParamsWithTimeout creates a new IamManagerChangePasswordParams object
// with the ability to set a timeout on a request.
func NewIamManagerChangePasswordParamsWithTimeout(timeout time.Duration) *IamManagerChangePasswordParams {
	return &IamManagerChangePasswordParams{
		timeout: timeout,
	}
}

// NewIamManagerChangePasswordParamsWithContext creates a new IamManagerChangePasswordParams object
// with the ability to set a context for a request.
func NewIamManagerChangePasswordParamsWithContext(ctx context.Context) *IamManagerChangePasswordParams {
	return &IamManagerChangePasswordParams{
		Context: ctx,
	}
}

// NewIamManagerChangePasswordParamsWithHTTPClient creates a new IamManagerChangePasswordParams object
// with the ability to set a custom HTTPClient for a request.
func NewIamManagerChangePasswordParamsWithHTTPClient(client *http.Client) *IamManagerChangePasswordParams {
	return &IamManagerChangePasswordParams{
		HTTPClient: client,
	}
}

/*
IamManagerChangePasswordParams contains all the parameters to send to the API endpoint

	for the iam manager change password operation.

	Typically these are written to a http.Request.
*/
type IamManagerChangePasswordParams struct {

	// Body.
	Body *models.NewbillingChangePasswdRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the iam manager change password params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *IamManagerChangePasswordParams) WithDefaults() *IamManagerChangePasswordParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the iam manager change password params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *IamManagerChangePasswordParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the iam manager change password params
func (o *IamManagerChangePasswordParams) WithTimeout(timeout time.Duration) *IamManagerChangePasswordParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the iam manager change password params
func (o *IamManagerChangePasswordParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the iam manager change password params
func (o *IamManagerChangePasswordParams) WithContext(ctx context.Context) *IamManagerChangePasswordParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the iam manager change password params
func (o *IamManagerChangePasswordParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the iam manager change password params
func (o *IamManagerChangePasswordParams) WithHTTPClient(client *http.Client) *IamManagerChangePasswordParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the iam manager change password params
func (o *IamManagerChangePasswordParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the iam manager change password params
func (o *IamManagerChangePasswordParams) WithBody(body *models.NewbillingChangePasswdRequest) *IamManagerChangePasswordParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the iam manager change password params
func (o *IamManagerChangePasswordParams) SetBody(body *models.NewbillingChangePasswdRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *IamManagerChangePasswordParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
