// Code generated by go-swagger; DO NOT EDIT.

package iam_manager

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewIamManagerDescribeTokenParams creates a new IamManagerDescribeTokenParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewIamManagerDescribeTokenParams() *IamManagerDescribeTokenParams {
	return &IamManagerDescribeTokenParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewIamManagerDescribeTokenParamsWithTimeout creates a new IamManagerDescribeTokenParams object
// with the ability to set a timeout on a request.
func NewIamManagerDescribeTokenParamsWithTimeout(timeout time.Duration) *IamManagerDescribeTokenParams {
	return &IamManagerDescribeTokenParams{
		timeout: timeout,
	}
}

// NewIamManagerDescribeTokenParamsWithContext creates a new IamManagerDescribeTokenParams object
// with the ability to set a context for a request.
func NewIamManagerDescribeTokenParamsWithContext(ctx context.Context) *IamManagerDescribeTokenParams {
	return &IamManagerDescribeTokenParams{
		Context: ctx,
	}
}

// NewIamManagerDescribeTokenParamsWithHTTPClient creates a new IamManagerDescribeTokenParams object
// with the ability to set a custom HTTPClient for a request.
func NewIamManagerDescribeTokenParamsWithHTTPClient(client *http.Client) *IamManagerDescribeTokenParams {
	return &IamManagerDescribeTokenParams{
		HTTPClient: client,
	}
}

/*
IamManagerDescribeTokenParams contains all the parameters to send to the API endpoint

	for the iam manager describe token operation.

	Typically these are written to a http.Request.
*/
type IamManagerDescribeTokenParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the iam manager describe token params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *IamManagerDescribeTokenParams) WithDefaults() *IamManagerDescribeTokenParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the iam manager describe token params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *IamManagerDescribeTokenParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the iam manager describe token params
func (o *IamManagerDescribeTokenParams) WithTimeout(timeout time.Duration) *IamManagerDescribeTokenParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the iam manager describe token params
func (o *IamManagerDescribeTokenParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the iam manager describe token params
func (o *IamManagerDescribeTokenParams) WithContext(ctx context.Context) *IamManagerDescribeTokenParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the iam manager describe token params
func (o *IamManagerDescribeTokenParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the iam manager describe token params
func (o *IamManagerDescribeTokenParams) WithHTTPClient(client *http.Client) *IamManagerDescribeTokenParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the iam manager describe token params
func (o *IamManagerDescribeTokenParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *IamManagerDescribeTokenParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
