// Code generated by go-swagger; DO NOT EDIT.

package iam_manager

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/KubeSphereCloud/newbilling-client-go/models"
)

// IamManagerModifyActionReader is a Reader for the IamManagerModifyAction structure.
type IamManagerModifyActionReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *IamManagerModifyActionReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewIamManagerModifyActionOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewIamManagerModifyActionDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewIamManagerModifyActionOK creates a IamManagerModifyActionOK with default headers values
func NewIamManagerModifyActionOK() *IamManagerModifyActionOK {
	return &IamManagerModifyActionOK{}
}

/*
IamManagerModifyActionOK describes a response with status code 200, with default header values.

A successful response.
*/
type IamManagerModifyActionOK struct {
	Payload *models.NewbillingModifyActionResponse
}

// IsSuccess returns true when this iam manager modify action o k response has a 2xx status code
func (o *IamManagerModifyActionOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this iam manager modify action o k response has a 3xx status code
func (o *IamManagerModifyActionOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this iam manager modify action o k response has a 4xx status code
func (o *IamManagerModifyActionOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this iam manager modify action o k response has a 5xx status code
func (o *IamManagerModifyActionOK) IsServerError() bool {
	return false
}

// IsCode returns true when this iam manager modify action o k response a status code equal to that given
func (o *IamManagerModifyActionOK) IsCode(code int) bool {
	return code == 200
}

func (o *IamManagerModifyActionOK) Error() string {
	return fmt.Sprintf("[PATCH /v1/actions][%d] iamManagerModifyActionOK  %+v", 200, o.Payload)
}

func (o *IamManagerModifyActionOK) String() string {
	return fmt.Sprintf("[PATCH /v1/actions][%d] iamManagerModifyActionOK  %+v", 200, o.Payload)
}

func (o *IamManagerModifyActionOK) GetPayload() *models.NewbillingModifyActionResponse {
	return o.Payload
}

func (o *IamManagerModifyActionOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.NewbillingModifyActionResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewIamManagerModifyActionDefault creates a IamManagerModifyActionDefault with default headers values
func NewIamManagerModifyActionDefault(code int) *IamManagerModifyActionDefault {
	return &IamManagerModifyActionDefault{
		_statusCode: code,
	}
}

/*
IamManagerModifyActionDefault describes a response with status code -1, with default header values.

An unexpected error response
*/
type IamManagerModifyActionDefault struct {
	_statusCode int

	Payload *models.RuntimeError
}

// Code gets the status code for the iam manager modify action default response
func (o *IamManagerModifyActionDefault) Code() int {
	return o._statusCode
}

// IsSuccess returns true when this iam manager modify action default response has a 2xx status code
func (o *IamManagerModifyActionDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this iam manager modify action default response has a 3xx status code
func (o *IamManagerModifyActionDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this iam manager modify action default response has a 4xx status code
func (o *IamManagerModifyActionDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this iam manager modify action default response has a 5xx status code
func (o *IamManagerModifyActionDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this iam manager modify action default response a status code equal to that given
func (o *IamManagerModifyActionDefault) IsCode(code int) bool {
	return o._statusCode == code
}

func (o *IamManagerModifyActionDefault) Error() string {
	return fmt.Sprintf("[PATCH /v1/actions][%d] IamManager_ModifyAction default  %+v", o._statusCode, o.Payload)
}

func (o *IamManagerModifyActionDefault) String() string {
	return fmt.Sprintf("[PATCH /v1/actions][%d] IamManager_ModifyAction default  %+v", o._statusCode, o.Payload)
}

func (o *IamManagerModifyActionDefault) GetPayload() *models.RuntimeError {
	return o.Payload
}

func (o *IamManagerModifyActionDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RuntimeError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
