// Code generated by go-swagger; DO NOT EDIT.

package iam_manager

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewIamManagerDescribeUserAccessSystemsParams creates a new IamManagerDescribeUserAccessSystemsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewIamManagerDescribeUserAccessSystemsParams() *IamManagerDescribeUserAccessSystemsParams {
	return &IamManagerDescribeUserAccessSystemsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewIamManagerDescribeUserAccessSystemsParamsWithTimeout creates a new IamManagerDescribeUserAccessSystemsParams object
// with the ability to set a timeout on a request.
func NewIamManagerDescribeUserAccessSystemsParamsWithTimeout(timeout time.Duration) *IamManagerDescribeUserAccessSystemsParams {
	return &IamManagerDescribeUserAccessSystemsParams{
		timeout: timeout,
	}
}

// NewIamManagerDescribeUserAccessSystemsParamsWithContext creates a new IamManagerDescribeUserAccessSystemsParams object
// with the ability to set a context for a request.
func NewIamManagerDescribeUserAccessSystemsParamsWithContext(ctx context.Context) *IamManagerDescribeUserAccessSystemsParams {
	return &IamManagerDescribeUserAccessSystemsParams{
		Context: ctx,
	}
}

// NewIamManagerDescribeUserAccessSystemsParamsWithHTTPClient creates a new IamManagerDescribeUserAccessSystemsParams object
// with the ability to set a custom HTTPClient for a request.
func NewIamManagerDescribeUserAccessSystemsParamsWithHTTPClient(client *http.Client) *IamManagerDescribeUserAccessSystemsParams {
	return &IamManagerDescribeUserAccessSystemsParams{
		HTTPClient: client,
	}
}

/*
IamManagerDescribeUserAccessSystemsParams contains all the parameters to send to the API endpoint

	for the iam manager describe user access systems operation.

	Typically these are written to a http.Request.
*/
type IamManagerDescribeUserAccessSystemsParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the iam manager describe user access systems params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *IamManagerDescribeUserAccessSystemsParams) WithDefaults() *IamManagerDescribeUserAccessSystemsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the iam manager describe user access systems params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *IamManagerDescribeUserAccessSystemsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the iam manager describe user access systems params
func (o *IamManagerDescribeUserAccessSystemsParams) WithTimeout(timeout time.Duration) *IamManagerDescribeUserAccessSystemsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the iam manager describe user access systems params
func (o *IamManagerDescribeUserAccessSystemsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the iam manager describe user access systems params
func (o *IamManagerDescribeUserAccessSystemsParams) WithContext(ctx context.Context) *IamManagerDescribeUserAccessSystemsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the iam manager describe user access systems params
func (o *IamManagerDescribeUserAccessSystemsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the iam manager describe user access systems params
func (o *IamManagerDescribeUserAccessSystemsParams) WithHTTPClient(client *http.Client) *IamManagerDescribeUserAccessSystemsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the iam manager describe user access systems params
func (o *IamManagerDescribeUserAccessSystemsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *IamManagerDescribeUserAccessSystemsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
