// Code generated by go-swagger; DO NOT EDIT.

package iam_manager

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/KubeSphereCloud/newbilling-client-go/models"
)

// IamManagerChangePasswordReader is a Reader for the IamManagerChangePassword structure.
type IamManagerChangePasswordReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *IamManagerChangePasswordReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewIamManagerChangePasswordOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewIamManagerChangePasswordDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewIamManagerChangePasswordOK creates a IamManagerChangePasswordOK with default headers values
func NewIamManagerChangePasswordOK() *IamManagerChangePasswordOK {
	return &IamManagerChangePasswordOK{}
}

/*
IamManagerChangePasswordOK describes a response with status code 200, with default header values.

A successful response.
*/
type IamManagerChangePasswordOK struct {
	Payload *models.NewbillingChangePasswdResponse
}

// IsSuccess returns true when this iam manager change password o k response has a 2xx status code
func (o *IamManagerChangePasswordOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this iam manager change password o k response has a 3xx status code
func (o *IamManagerChangePasswordOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this iam manager change password o k response has a 4xx status code
func (o *IamManagerChangePasswordOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this iam manager change password o k response has a 5xx status code
func (o *IamManagerChangePasswordOK) IsServerError() bool {
	return false
}

// IsCode returns true when this iam manager change password o k response a status code equal to that given
func (o *IamManagerChangePasswordOK) IsCode(code int) bool {
	return code == 200
}

func (o *IamManagerChangePasswordOK) Error() string {
	return fmt.Sprintf("[PUT /v1/users/password][%d] iamManagerChangePasswordOK  %+v", 200, o.Payload)
}

func (o *IamManagerChangePasswordOK) String() string {
	return fmt.Sprintf("[PUT /v1/users/password][%d] iamManagerChangePasswordOK  %+v", 200, o.Payload)
}

func (o *IamManagerChangePasswordOK) GetPayload() *models.NewbillingChangePasswdResponse {
	return o.Payload
}

func (o *IamManagerChangePasswordOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.NewbillingChangePasswdResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewIamManagerChangePasswordDefault creates a IamManagerChangePasswordDefault with default headers values
func NewIamManagerChangePasswordDefault(code int) *IamManagerChangePasswordDefault {
	return &IamManagerChangePasswordDefault{
		_statusCode: code,
	}
}

/*
IamManagerChangePasswordDefault describes a response with status code -1, with default header values.

An unexpected error response
*/
type IamManagerChangePasswordDefault struct {
	_statusCode int

	Payload *models.RuntimeError
}

// Code gets the status code for the iam manager change password default response
func (o *IamManagerChangePasswordDefault) Code() int {
	return o._statusCode
}

// IsSuccess returns true when this iam manager change password default response has a 2xx status code
func (o *IamManagerChangePasswordDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this iam manager change password default response has a 3xx status code
func (o *IamManagerChangePasswordDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this iam manager change password default response has a 4xx status code
func (o *IamManagerChangePasswordDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this iam manager change password default response has a 5xx status code
func (o *IamManagerChangePasswordDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this iam manager change password default response a status code equal to that given
func (o *IamManagerChangePasswordDefault) IsCode(code int) bool {
	return o._statusCode == code
}

func (o *IamManagerChangePasswordDefault) Error() string {
	return fmt.Sprintf("[PUT /v1/users/password][%d] IamManager_ChangePassword default  %+v", o._statusCode, o.Payload)
}

func (o *IamManagerChangePasswordDefault) String() string {
	return fmt.Sprintf("[PUT /v1/users/password][%d] IamManager_ChangePassword default  %+v", o._statusCode, o.Payload)
}

func (o *IamManagerChangePasswordDefault) GetPayload() *models.RuntimeError {
	return o.Payload
}

func (o *IamManagerChangePasswordDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RuntimeError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
