// Code generated by go-swagger; DO NOT EDIT.

package iam_manager

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/KubeSphereCloud/newbilling-client-go/models"
)

// NewIamManagerResetPwdSendEmailParams creates a new IamManagerResetPwdSendEmailParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewIamManagerResetPwdSendEmailParams() *IamManagerResetPwdSendEmailParams {
	return &IamManagerResetPwdSendEmailParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewIamManagerResetPwdSendEmailParamsWithTimeout creates a new IamManagerResetPwdSendEmailParams object
// with the ability to set a timeout on a request.
func NewIamManagerResetPwdSendEmailParamsWithTimeout(timeout time.Duration) *IamManagerResetPwdSendEmailParams {
	return &IamManagerResetPwdSendEmailParams{
		timeout: timeout,
	}
}

// NewIamManagerResetPwdSendEmailParamsWithContext creates a new IamManagerResetPwdSendEmailParams object
// with the ability to set a context for a request.
func NewIamManagerResetPwdSendEmailParamsWithContext(ctx context.Context) *IamManagerResetPwdSendEmailParams {
	return &IamManagerResetPwdSendEmailParams{
		Context: ctx,
	}
}

// NewIamManagerResetPwdSendEmailParamsWithHTTPClient creates a new IamManagerResetPwdSendEmailParams object
// with the ability to set a custom HTTPClient for a request.
func NewIamManagerResetPwdSendEmailParamsWithHTTPClient(client *http.Client) *IamManagerResetPwdSendEmailParams {
	return &IamManagerResetPwdSendEmailParams{
		HTTPClient: client,
	}
}

/*
IamManagerResetPwdSendEmailParams contains all the parameters to send to the API endpoint

	for the iam manager reset pwd send email operation.

	Typically these are written to a http.Request.
*/
type IamManagerResetPwdSendEmailParams struct {

	// Body.
	Body *models.NewbillingResetPwdSendEmailRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the iam manager reset pwd send email params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *IamManagerResetPwdSendEmailParams) WithDefaults() *IamManagerResetPwdSendEmailParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the iam manager reset pwd send email params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *IamManagerResetPwdSendEmailParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the iam manager reset pwd send email params
func (o *IamManagerResetPwdSendEmailParams) WithTimeout(timeout time.Duration) *IamManagerResetPwdSendEmailParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the iam manager reset pwd send email params
func (o *IamManagerResetPwdSendEmailParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the iam manager reset pwd send email params
func (o *IamManagerResetPwdSendEmailParams) WithContext(ctx context.Context) *IamManagerResetPwdSendEmailParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the iam manager reset pwd send email params
func (o *IamManagerResetPwdSendEmailParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the iam manager reset pwd send email params
func (o *IamManagerResetPwdSendEmailParams) WithHTTPClient(client *http.Client) *IamManagerResetPwdSendEmailParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the iam manager reset pwd send email params
func (o *IamManagerResetPwdSendEmailParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the iam manager reset pwd send email params
func (o *IamManagerResetPwdSendEmailParams) WithBody(body *models.NewbillingResetPwdSendEmailRequest) *IamManagerResetPwdSendEmailParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the iam manager reset pwd send email params
func (o *IamManagerResetPwdSendEmailParams) SetBody(body *models.NewbillingResetPwdSendEmailRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *IamManagerResetPwdSendEmailParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
