// Code generated by go-swagger; DO NOT EDIT.

package iam_manager

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/KubeSphereCloud/newbilling-client-go/models"
)

// IamManagerCreateRoleReader is a Reader for the IamManagerCreateRole structure.
type IamManagerCreateRoleReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *IamManagerCreateRoleReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewIamManagerCreateRoleOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewIamManagerCreateRoleDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewIamManagerCreateRoleOK creates a IamManagerCreateRoleOK with default headers values
func NewIamManagerCreateRoleOK() *IamManagerCreateRoleOK {
	return &IamManagerCreateRoleOK{}
}

/*
IamManagerCreateRoleOK describes a response with status code 200, with default header values.

A successful response.
*/
type IamManagerCreateRoleOK struct {
	Payload *models.NewbillingCreateRoleResponse
}

// IsSuccess returns true when this iam manager create role o k response has a 2xx status code
func (o *IamManagerCreateRoleOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this iam manager create role o k response has a 3xx status code
func (o *IamManagerCreateRoleOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this iam manager create role o k response has a 4xx status code
func (o *IamManagerCreateRoleOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this iam manager create role o k response has a 5xx status code
func (o *IamManagerCreateRoleOK) IsServerError() bool {
	return false
}

// IsCode returns true when this iam manager create role o k response a status code equal to that given
func (o *IamManagerCreateRoleOK) IsCode(code int) bool {
	return code == 200
}

func (o *IamManagerCreateRoleOK) Error() string {
	return fmt.Sprintf("[POST /v1/roles][%d] iamManagerCreateRoleOK  %+v", 200, o.Payload)
}

func (o *IamManagerCreateRoleOK) String() string {
	return fmt.Sprintf("[POST /v1/roles][%d] iamManagerCreateRoleOK  %+v", 200, o.Payload)
}

func (o *IamManagerCreateRoleOK) GetPayload() *models.NewbillingCreateRoleResponse {
	return o.Payload
}

func (o *IamManagerCreateRoleOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.NewbillingCreateRoleResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewIamManagerCreateRoleDefault creates a IamManagerCreateRoleDefault with default headers values
func NewIamManagerCreateRoleDefault(code int) *IamManagerCreateRoleDefault {
	return &IamManagerCreateRoleDefault{
		_statusCode: code,
	}
}

/*
IamManagerCreateRoleDefault describes a response with status code -1, with default header values.

An unexpected error response
*/
type IamManagerCreateRoleDefault struct {
	_statusCode int

	Payload *models.RuntimeError
}

// Code gets the status code for the iam manager create role default response
func (o *IamManagerCreateRoleDefault) Code() int {
	return o._statusCode
}

// IsSuccess returns true when this iam manager create role default response has a 2xx status code
func (o *IamManagerCreateRoleDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this iam manager create role default response has a 3xx status code
func (o *IamManagerCreateRoleDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this iam manager create role default response has a 4xx status code
func (o *IamManagerCreateRoleDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this iam manager create role default response has a 5xx status code
func (o *IamManagerCreateRoleDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this iam manager create role default response a status code equal to that given
func (o *IamManagerCreateRoleDefault) IsCode(code int) bool {
	return o._statusCode == code
}

func (o *IamManagerCreateRoleDefault) Error() string {
	return fmt.Sprintf("[POST /v1/roles][%d] IamManager_CreateRole default  %+v", o._statusCode, o.Payload)
}

func (o *IamManagerCreateRoleDefault) String() string {
	return fmt.Sprintf("[POST /v1/roles][%d] IamManager_CreateRole default  %+v", o._statusCode, o.Payload)
}

func (o *IamManagerCreateRoleDefault) GetPayload() *models.RuntimeError {
	return o.Payload
}

func (o *IamManagerCreateRoleDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RuntimeError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
