// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewbillingGetProductResponse newbilling get product response
//
// swagger:model newbillingGetProductResponse
type NewbillingGetProductResponse struct {

	// plan pricing set
	PlanPricingSet []*NewbillingPlanPricing `json:"plan_pricing_set"`

	// prod id
	ProdID string `json:"prod_id,omitempty"`

	// product
	Product *NewbillingProduct `json:"product,omitempty"`

	// product final price
	ProductFinalPrice float32 `json:"product_final_price,omitempty"`

	// product price
	ProductPrice float32 `json:"product_price,omitempty"`
}

// Validate validates this newbilling get product response
func (m *NewbillingGetProductResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validatePlanPricingSet(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateProduct(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *NewbillingGetProductResponse) validatePlanPricingSet(formats strfmt.Registry) error {
	if swag.IsZero(m.PlanPricingSet) { // not required
		return nil
	}

	for i := 0; i < len(m.PlanPricingSet); i++ {
		if swag.IsZero(m.PlanPricingSet[i]) { // not required
			continue
		}

		if m.PlanPricingSet[i] != nil {
			if err := m.PlanPricingSet[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("plan_pricing_set" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("plan_pricing_set" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *NewbillingGetProductResponse) validateProduct(formats strfmt.Registry) error {
	if swag.IsZero(m.Product) { // not required
		return nil
	}

	if m.Product != nil {
		if err := m.Product.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("product")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("product")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this newbilling get product response based on the context it is used
func (m *NewbillingGetProductResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidatePlanPricingSet(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateProduct(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *NewbillingGetProductResponse) contextValidatePlanPricingSet(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.PlanPricingSet); i++ {

		if m.PlanPricingSet[i] != nil {
			if err := m.PlanPricingSet[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("plan_pricing_set" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("plan_pricing_set" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *NewbillingGetProductResponse) contextValidateProduct(ctx context.Context, formats strfmt.Registry) error {

	if m.Product != nil {
		if err := m.Product.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("product")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("product")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *NewbillingGetProductResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *NewbillingGetProductResponse) UnmarshalBinary(b []byte) error {
	var res NewbillingGetProductResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
