// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewbillingModifyFilterNameRequest 修改条件请求信息 -  修改名称。
//
// swagger:model newbillingModifyFilterNameRequest
type NewbillingModifyFilterNameRequest struct {

	// 接入系统ID仅super user有效，接入系统管理员/成员会默认用当前登陆的接入系统
	AccessSysID string `json:"access_sys_id,omitempty"`

	// 条件ID @gotags:valid:"Required"
	FilterID string `json:"filter_id,omitempty"`

	// 条件名称
	Name string `json:"name,omitempty"`
}

// Validate validates this newbilling modify filter name request
func (m *NewbillingModifyFilterNameRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this newbilling modify filter name request based on context it is used
func (m *NewbillingModifyFilterNameRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *NewbillingModifyFilterNameRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *NewbillingModifyFilterNameRequest) UnmarshalBinary(b []byte) error {
	var res NewbillingModifyFilterNameRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
