// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewbillingDeleteStrategiesResponse 删除策略返回信息
//
// swagger:model newbillingDeleteStrategiesResponse
type NewbillingDeleteStrategiesResponse struct {

	// 策略ID列表
	StrategyID []string `json:"strategy_id"`
}

// Validate validates this newbilling delete strategies response
func (m *NewbillingDeleteStrategiesResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this newbilling delete strategies response based on context it is used
func (m *NewbillingDeleteStrategiesResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *NewbillingDeleteStrategiesResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *NewbillingDeleteStrategiesResponse) UnmarshalBinary(b []byte) error {
	var res NewbillingDeleteStrategiesResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
