// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewbillingPerformBillingJobResponse 执行计费任务返回信息（用于调度系统的回调）
//
// swagger:model newbillingPerformBillingJobResponse
type NewbillingPerformBillingJobResponse struct {

	// 计费任务ID
	BillingJobID string `json:"billing_job_id,omitempty"`
}

// Validate validates this newbilling perform billing job response
func (m *NewbillingPerformBillingJobResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this newbilling perform billing job response based on context it is used
func (m *NewbillingPerformBillingJobResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *NewbillingPerformBillingJobResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *NewbillingPerformBillingJobResponse) UnmarshalBinary(b []byte) error {
	var res NewbillingPerformBillingJobResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
