// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewbillingRefreshOpenAPITokenResponse newbilling refresh open Api token response
//
// swagger:model newbillingRefreshOpenApiTokenResponse
type NewbillingRefreshOpenAPITokenResponse struct {

	// roundup
	Roundup string `json:"roundup,omitempty"`

	// token
	Token string `json:"token,omitempty"`
}

// Validate validates this newbilling refresh open Api token response
func (m *NewbillingRefreshOpenAPITokenResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this newbilling refresh open Api token response based on context it is used
func (m *NewbillingRefreshOpenAPITokenResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *NewbillingRefreshOpenAPITokenResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *NewbillingRefreshOpenAPITokenResponse) UnmarshalBinary(b []byte) error {
	var res NewbillingRefreshOpenAPITokenResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
