// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewbillingComponentOfPricingSimpleStrategy newbilling component of pricing simple strategy
//
// swagger:model newbillingComponentOfPricingSimpleStrategy
type NewbillingComponentOfPricingSimpleStrategy struct {

	// 折扣
	BasicDiscount float32 `json:"basic_discount,omitempty"`

	// 总价 策略公式
	CostExpression string `json:"cost_expression,omitempty"`

	// 条件表达式 前端不填
	FilterExpression string `json:"filter_expression,omitempty"`

	// 条件
	Filters []*NewbillingComponentOfPricingSimpleFilter `json:"filters"`

	// 策略名称
	Name string `json:"name,omitempty"`

	// 策略标记
	Remark string `json:"remark,omitempty"`

	// 策略code
	StrategyCode string `json:"strategy_code,omitempty"`

	// 策略ID 编辑时不能为空
	StrategyID string `json:"strategy_id,omitempty"`
}

// Validate validates this newbilling component of pricing simple strategy
func (m *NewbillingComponentOfPricingSimpleStrategy) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateFilters(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *NewbillingComponentOfPricingSimpleStrategy) validateFilters(formats strfmt.Registry) error {
	if swag.IsZero(m.Filters) { // not required
		return nil
	}

	for i := 0; i < len(m.Filters); i++ {
		if swag.IsZero(m.Filters[i]) { // not required
			continue
		}

		if m.Filters[i] != nil {
			if err := m.Filters[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("filters" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("filters" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this newbilling component of pricing simple strategy based on the context it is used
func (m *NewbillingComponentOfPricingSimpleStrategy) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateFilters(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *NewbillingComponentOfPricingSimpleStrategy) contextValidateFilters(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Filters); i++ {

		if m.Filters[i] != nil {
			if err := m.Filters[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("filters" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("filters" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *NewbillingComponentOfPricingSimpleStrategy) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *NewbillingComponentOfPricingSimpleStrategy) UnmarshalBinary(b []byte) error {
	var res NewbillingComponentOfPricingSimpleStrategy
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
