// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewbillingCreateChargeResponse 创建支付记录返回信息
//
// swagger:model newbillingCreateChargeResponse
type NewbillingCreateChargeResponse struct {

	// 支付记录ID
	ChargeID string `json:"charge_id,omitempty"`

	// 支付结果 0. NORMAL 正常扣费成功 1. RET_NO_MONEY 余额不足，扣费失败 2. CHARGED_RET_NO_MONEY 余额不足, 强制扣费成功
	ChargeResult string `json:"charge_result,omitempty"`
}

// Validate validates this newbilling create charge response
func (m *NewbillingCreateChargeResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this newbilling create charge response based on context it is used
func (m *NewbillingCreateChargeResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *NewbillingCreateChargeResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *NewbillingCreateChargeResponse) UnmarshalBinary(b []byte) error {
	var res NewbillingCreateChargeResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
