// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewbillingCreateStrategyResponse 创建策略返回信息
//
// swagger:model newbillingCreateStrategyResponse
type NewbillingCreateStrategyResponse struct {

	// 策略ID
	StrategyID string `json:"strategy_id,omitempty"`
}

// Validate validates this newbilling create strategy response
func (m *NewbillingCreateStrategyResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this newbilling create strategy response based on context it is used
func (m *NewbillingCreateStrategyResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *NewbillingCreateStrategyResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *NewbillingCreateStrategyResponse) UnmarshalBinary(b []byte) error {
	var res NewbillingCreateStrategyResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
