// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewbillingCreateCatalogRequest 创建产品目录请求信息
//
// swagger:model newbillingCreateCatalogRequest
type NewbillingCreateCatalogRequest struct {

	// 接入系统ID仅super user有效，接入系统管理员/成员会默认用当前登陆的接入系统
	AccessSysID string `json:"access_sys_id,omitempty"`

	// 产品目录编码
	CataCode string `json:"cata_code,omitempty"`

	// 产品目录名称 @gotags:valid:"Required;MaxSize(30)"
	Name string `json:"name,omitempty"`

	// 产品目录的父目录ID
	ParentCataID string `json:"parent_cata_id,omitempty"`
}

// Validate validates this newbilling create catalog request
func (m *NewbillingCreateCatalogRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this newbilling create catalog request based on context it is used
func (m *NewbillingCreateCatalogRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *NewbillingCreateCatalogRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *NewbillingCreateCatalogRequest) UnmarshalBinary(b []byte) error {
	var res NewbillingCreateCatalogRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
