// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewbillingChargePrdOrderResponse 支付主订单返回信息
//
// swagger:model newbillingChargePrdOrderResponse
type NewbillingChargePrdOrderResponse struct {

	// 主订单ID
	OrderID string `json:"order_id,omitempty"`
}

// Validate validates this newbilling charge prd order response
func (m *NewbillingChargePrdOrderResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this newbilling charge prd order response based on context it is used
func (m *NewbillingChargePrdOrderResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *NewbillingChargePrdOrderResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *NewbillingChargePrdOrderResponse) UnmarshalBinary(b []byte) error {
	var res NewbillingChargePrdOrderResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
