// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewbillingModifyFilterRequest 修改条件请求信息
//
// swagger:model newbillingModifyFilterRequest
type NewbillingModifyFilterRequest struct {

	// 接入系统ID仅super user有效，接入系统管理员/成员会默认用当前登陆的接入系统
	AccessSysID string `json:"access_sys_id,omitempty"`

	// 条件描述
	Description string `json:"description,omitempty"`

	// 条件编码
	FilterCode string `json:"filter_code,omitempty"`

	// 条件ID @gotags:valid:"Required"
	FilterID string `json:"filter_id,omitempty"`

	// 条件左值
	LeftValue string `json:"left_value,omitempty"`

	// 条件名称
	Name string `json:"name,omitempty"`

	// 条件操作符
	Operator string `json:"operator,omitempty"`

	// 产品ID
	ProdID string `json:"prod_id,omitempty"`

	// 条件备注
	Remark string `json:"remark,omitempty"`

	// 条件右值
	RightValue string `json:"right_value,omitempty"`
}

// Validate validates this newbilling modify filter request
func (m *NewbillingModifyFilterRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this newbilling modify filter request based on context it is used
func (m *NewbillingModifyFilterRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *NewbillingModifyFilterRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *NewbillingModifyFilterRequest) UnmarshalBinary(b []byte) error {
	var res NewbillingModifyFilterRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
