// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewbillingPrepayStripeRequest newbilling prepay stripe request
//
// swagger:model newbillingPrepayStripeRequest
type NewbillingPrepayStripeRequest struct {

	// access sys id
	AccessSysID string `json:"access_sys_id,omitempty"`

	// code
	Code string `json:"code,omitempty"`
}

// Validate validates this newbilling prepay stripe request
func (m *NewbillingPrepayStripeRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this newbilling prepay stripe request based on context it is used
func (m *NewbillingPrepayStripeRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *NewbillingPrepayStripeRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *NewbillingPrepayStripeRequest) UnmarshalBinary(b []byte) error {
	var res NewbillingPrepayStripeRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
