// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewbillingModifyFilterResponse 修改条件返回信息
//
// swagger:model newbillingModifyFilterResponse
type NewbillingModifyFilterResponse struct {

	// 条件ID
	FilterID string `json:"filter_id,omitempty"`
}

// Validate validates this newbilling modify filter response
func (m *NewbillingModifyFilterResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this newbilling modify filter response based on context it is used
func (m *NewbillingModifyFilterResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *NewbillingModifyFilterResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *NewbillingModifyFilterResponse) UnmarshalBinary(b []byte) error {
	var res NewbillingModifyFilterResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
