// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewbillingDescribeConsumeOrdersResponse newbilling describe consume orders response
//
// swagger:model newbillingDescribeConsumeOrdersResponse
type NewbillingDescribeConsumeOrdersResponse struct {

	// 返回结果列表
	ConsumeOrderSet []*NewbillingConsumeOrder `json:"consume_order_set"`

	// 匹配条件的结果总数
	Total int64 `json:"total,omitempty"`
}

// Validate validates this newbilling describe consume orders response
func (m *NewbillingDescribeConsumeOrdersResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateConsumeOrderSet(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *NewbillingDescribeConsumeOrdersResponse) validateConsumeOrderSet(formats strfmt.Registry) error {
	if swag.IsZero(m.ConsumeOrderSet) { // not required
		return nil
	}

	for i := 0; i < len(m.ConsumeOrderSet); i++ {
		if swag.IsZero(m.ConsumeOrderSet[i]) { // not required
			continue
		}

		if m.ConsumeOrderSet[i] != nil {
			if err := m.ConsumeOrderSet[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("consume_order_set" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("consume_order_set" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this newbilling describe consume orders response based on the context it is used
func (m *NewbillingDescribeConsumeOrdersResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateConsumeOrderSet(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *NewbillingDescribeConsumeOrdersResponse) contextValidateConsumeOrderSet(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.ConsumeOrderSet); i++ {

		if m.ConsumeOrderSet[i] != nil {
			if err := m.ConsumeOrderSet[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("consume_order_set" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("consume_order_set" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *NewbillingDescribeConsumeOrdersResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *NewbillingDescribeConsumeOrdersResponse) UnmarshalBinary(b []byte) error {
	var res NewbillingDescribeConsumeOrdersResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
