// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewbillingCustomerTransactResponse newbilling customer transact response
//
// swagger:model newbillingCustomerTransactResponse
type NewbillingCustomerTransactResponse struct {

	// trans result
	TransResult string `json:"trans_result,omitempty"`
}

// Validate validates this newbilling customer transact response
func (m *NewbillingCustomerTransactResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this newbilling customer transact response based on context it is used
func (m *NewbillingCustomerTransactResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *NewbillingCustomerTransactResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *NewbillingCustomerTransactResponse) UnmarshalBinary(b []byte) error {
	var res NewbillingCustomerTransactResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
