// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewbillingModifyComponentResponse 修改计费项返回信息
//
// swagger:model newbillingModifyComponentResponse
type NewbillingModifyComponentResponse struct {

	// 计费项ID
	CompID string `json:"comp_id,omitempty"`
}

// Validate validates this newbilling modify component response
func (m *NewbillingModifyComponentResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this newbilling modify component response based on context it is used
func (m *NewbillingModifyComponentResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *NewbillingModifyComponentResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *NewbillingModifyComponentResponse) UnmarshalBinary(b []byte) error {
	var res NewbillingModifyComponentResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
