// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewbillingDescribeProductsResponse 查询产品返回信息
//
// swagger:model newbillingDescribeProductsResponse
type NewbillingDescribeProductsResponse struct {

	// 返回结果列表
	ProductSet []*NewbillingProduct `json:"product_set"`

	// 返回总数
	Total int64 `json:"total,omitempty"`
}

// Validate validates this newbilling describe products response
func (m *NewbillingDescribeProductsResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateProductSet(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *NewbillingDescribeProductsResponse) validateProductSet(formats strfmt.Registry) error {
	if swag.IsZero(m.ProductSet) { // not required
		return nil
	}

	for i := 0; i < len(m.ProductSet); i++ {
		if swag.IsZero(m.ProductSet[i]) { // not required
			continue
		}

		if m.ProductSet[i] != nil {
			if err := m.ProductSet[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("product_set" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("product_set" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this newbilling describe products response based on the context it is used
func (m *NewbillingDescribeProductsResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateProductSet(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *NewbillingDescribeProductsResponse) contextValidateProductSet(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.ProductSet); i++ {

		if m.ProductSet[i] != nil {
			if err := m.ProductSet[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("product_set" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("product_set" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *NewbillingDescribeProductsResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *NewbillingDescribeProductsResponse) UnmarshalBinary(b []byte) error {
	var res NewbillingDescribeProductsResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
