// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// NewbillingStartBillingJobsResponse newbilling start billing jobs response
//
// swagger:model newbillingStartBillingJobsResponse
type NewbillingStartBillingJobsResponse interface{}
