// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewbillingDescribeTokenResponse 查询TOKEN返回信息
//
// swagger:model newbillingDescribeTokenResponse
type NewbillingDescribeTokenResponse struct {

	// 接入平台ID
	AccessSysID string `json:"access_sys_id,omitempty"`

	// 用户token
	Token string `json:"token,omitempty"`

	// 用户ID
	UserID string `json:"user_id,omitempty"`
}

// Validate validates this newbilling describe token response
func (m *NewbillingDescribeTokenResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this newbilling describe token response based on context it is used
func (m *NewbillingDescribeTokenResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *NewbillingDescribeTokenResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *NewbillingDescribeTokenResponse) UnmarshalBinary(b []byte) error {
	var res NewbillingDescribeTokenResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
