// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewbillingUnMappingComponentRequest 取消计费项转换请求信息
//
// swagger:model newbillingUnMappingComponentRequest
type NewbillingUnMappingComponentRequest struct {

	// 取消转换的计费项ID @gotags: valid:"Required"
	CompID string `json:"comp_id,omitempty"`
}

// Validate validates this newbilling un mapping component request
func (m *NewbillingUnMappingComponentRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this newbilling un mapping component request based on context it is used
func (m *NewbillingUnMappingComponentRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *NewbillingUnMappingComponentRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *NewbillingUnMappingComponentRequest) UnmarshalBinary(b []byte) error {
	var res NewbillingUnMappingComponentRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
