// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewbillingDeleteAttributesResponse 删除属性返回信息
//
// swagger:model newbillingDeleteAttributesResponse
type NewbillingDeleteAttributesResponse struct {

	// 属性ID列表
	AttrID []string `json:"attr_id"`
}

// Validate validates this newbilling delete attributes response
func (m *NewbillingDeleteAttributesResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this newbilling delete attributes response based on context it is used
func (m *NewbillingDeleteAttributesResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *NewbillingDeleteAttributesResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *NewbillingDeleteAttributesResponse) UnmarshalBinary(b []byte) error {
	var res NewbillingDeleteAttributesResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
