// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewbillingChangePasswdResponse 修改用户密码返回信息
//
// swagger:model newbillingChangePasswdResponse
type NewbillingChangePasswdResponse struct {

	// 修改的用户ID
	UserID string `json:"user_id,omitempty"`
}

// Validate validates this newbilling change passwd response
func (m *NewbillingChangePasswdResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this newbilling change passwd response based on context it is used
func (m *NewbillingChangePasswdResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *NewbillingChangePasswdResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *NewbillingChangePasswdResponse) UnmarshalBinary(b []byte) error {
	var res NewbillingChangePasswdResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
