// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewbillingBindingRoleAction 角色操作绑定基本信息
//
// swagger:model newbillingBindingRoleAction
type NewbillingBindingRoleAction struct {

	// 角色要绑定的操作列表
	APIID []string `json:"api_id"`

	// 角色ID
	RoleID string `json:"role_id,omitempty"`
}

// Validate validates this newbilling binding role action
func (m *NewbillingBindingRoleAction) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this newbilling binding role action based on context it is used
func (m *NewbillingBindingRoleAction) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *NewbillingBindingRoleAction) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *NewbillingBindingRoleAction) UnmarshalBinary(b []byte) error {
	var res NewbillingBindingRoleAction
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
