// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewbillingBindingMembersRolesResponse 用户角色绑定返回信息
//
// swagger:model newbillingBindingMembersRolesResponse
type NewbillingBindingMembersRolesResponse struct {

	// 绑定是否成功
	Ok bool `json:"ok,omitempty"`
}

// Validate validates this newbilling binding members roles response
func (m *NewbillingBindingMembersRolesResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this newbilling binding members roles response based on context it is used
func (m *NewbillingBindingMembersRolesResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *NewbillingBindingMembersRolesResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *NewbillingBindingMembersRolesResponse) UnmarshalBinary(b []byte) error {
	var res NewbillingBindingMembersRolesResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
