// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewbillingBindingMembersRolesRequest 用户角色绑定请求信息
//
// swagger:model newbillingBindingMembersRolesRequest
type NewbillingBindingMembersRolesRequest struct {

	// 用户角色绑定列表
	BindingMemberRole []*NewbillingBindingMemberRole `json:"binding_member_role"`
}

// Validate validates this newbilling binding members roles request
func (m *NewbillingBindingMembersRolesRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateBindingMemberRole(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *NewbillingBindingMembersRolesRequest) validateBindingMemberRole(formats strfmt.Registry) error {
	if swag.IsZero(m.BindingMemberRole) { // not required
		return nil
	}

	for i := 0; i < len(m.BindingMemberRole); i++ {
		if swag.IsZero(m.BindingMemberRole[i]) { // not required
			continue
		}

		if m.BindingMemberRole[i] != nil {
			if err := m.BindingMemberRole[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("binding_member_role" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("binding_member_role" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this newbilling binding members roles request based on the context it is used
func (m *NewbillingBindingMembersRolesRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateBindingMemberRole(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *NewbillingBindingMembersRolesRequest) contextValidateBindingMemberRole(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.BindingMemberRole); i++ {

		if m.BindingMemberRole[i] != nil {
			if err := m.BindingMemberRole[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("binding_member_role" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("binding_member_role" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *NewbillingBindingMembersRolesRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *NewbillingBindingMembersRolesRequest) UnmarshalBinary(b []byte) error {
	var res NewbillingBindingMembersRolesRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
