// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// NewbillingStartCollectRequest newbilling start collect request
//
// swagger:model newbillingStartCollectRequest
type NewbillingStartCollectRequest struct {

	// 接入系统ID
	AccessSysID string `json:"access_sys_id,omitempty"`

	// 采集开始时间
	// Format: date-time
	CollectTime *strfmt.DateTime `json:"collect_time,omitempty"`

	// 产品ID
	ProdID string `json:"prod_id,omitempty"`

	// 资源ID
	ProdInstIDExt string `json:"prod_inst_id_ext,omitempty"`
}

// Validate validates this newbilling start collect request
func (m *NewbillingStartCollectRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCollectTime(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *NewbillingStartCollectRequest) validateCollectTime(formats strfmt.Registry) error {
	if swag.IsZero(m.CollectTime) { // not required
		return nil
	}

	if err := validate.FormatOf("collect_time", "body", "date-time", m.CollectTime.String(), formats); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this newbilling start collect request based on context it is used
func (m *NewbillingStartCollectRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *NewbillingStartCollectRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *NewbillingStartCollectRequest) UnmarshalBinary(b []byte) error {
	var res NewbillingStartCollectRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
