// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewbillingCreateCustomerCurrencyRequest 优惠券目前只支持newbilling中的customer
//
// swagger:model newbillingCreateCustomerCurrencyRequest
type NewbillingCreateCustomerCurrencyRequest struct {

	// access sys id
	AccessSysID string `json:"access_sys_id,omitempty"`

	// charge id
	ChargeID string `json:"charge_id,omitempty"`

	// currency type
	CurrencyType string `json:"currency_type,omitempty"`

	// currency value
	CurrencyValue float32 `json:"currency_value,omitempty"`

	// customer id
	CustomerID string `json:"customer_id,omitempty"`

	// duration
	Duration string `json:"duration,omitempty"`
}

// Validate validates this newbilling create customer currency request
func (m *NewbillingCreateCustomerCurrencyRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this newbilling create customer currency request based on context it is used
func (m *NewbillingCreateCustomerCurrencyRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *NewbillingCreateCustomerCurrencyRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *NewbillingCreateCustomerCurrencyRequest) UnmarshalBinary(b []byte) error {
	var res NewbillingCreateCustomerCurrencyRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
