// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewbillingResetPwdSendEmailResponse 用户重置密码发送邮件响应信息
//
// swagger:model newbillingResetPwdSendEmailResponse
type NewbillingResetPwdSendEmailResponse struct {

	// 用户重置密码CODE
	Code string `json:"code,omitempty"`

	// 是否发送成功
	Ok bool `json:"ok,omitempty"`
}

// Validate validates this newbilling reset pwd send email response
func (m *NewbillingResetPwdSendEmailResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this newbilling reset pwd send email response based on context it is used
func (m *NewbillingResetPwdSendEmailResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *NewbillingResetPwdSendEmailResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *NewbillingResetPwdSendEmailResponse) UnmarshalBinary(b []byte) error {
	var res NewbillingResetPwdSendEmailResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
