// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// NewbillingCreateCustomerResource newbilling create customer resource
//
// swagger:model newbillingCreateCustomerResource
type NewbillingCreateCustomerResource struct {

	// attr id
	AttrID string `json:"attr_id,omitempty"`

	// attr name
	AttrName string `json:"attr_name,omitempty"`

	// attr value
	AttrValue string `json:"attr_value,omitempty"`

	// duration
	Duration string `json:"duration,omitempty"`

	// expire time
	// Format: date-time
	ExpireTime strfmt.DateTime `json:"expire_time,omitempty"`

	// resource pkg type
	ResourcePkgType string `json:"resource_pkg_type,omitempty"`

	// start time
	// Format: date-time
	StartTime strfmt.DateTime `json:"start_time,omitempty"`

	// subs component id
	SubsComponentID string `json:"subs_component_id,omitempty"`

	// unit
	Unit string `json:"unit,omitempty"`

	// value type
	ValueType string `json:"value_type,omitempty"`
}

// Validate validates this newbilling create customer resource
func (m *NewbillingCreateCustomerResource) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateExpireTime(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateStartTime(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *NewbillingCreateCustomerResource) validateExpireTime(formats strfmt.Registry) error {
	if swag.IsZero(m.ExpireTime) { // not required
		return nil
	}

	if err := validate.FormatOf("expire_time", "body", "date-time", m.ExpireTime.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *NewbillingCreateCustomerResource) validateStartTime(formats strfmt.Registry) error {
	if swag.IsZero(m.StartTime) { // not required
		return nil
	}

	if err := validate.FormatOf("start_time", "body", "date-time", m.StartTime.String(), formats); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this newbilling create customer resource based on context it is used
func (m *NewbillingCreateCustomerResource) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *NewbillingCreateCustomerResource) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *NewbillingCreateCustomerResource) UnmarshalBinary(b []byte) error {
	var res NewbillingCreateCustomerResource
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
