// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewbillingRenewProdInstanceRequestRenewParams newbilling renew prod instance request renew params
//
// swagger:model newbillingRenewProdInstanceRequestRenewParams
type NewbillingRenewProdInstanceRequestRenewParams struct {

	// charge channel
	ChargeChannel string `json:"charge_channel,omitempty"`

	// duration
	Duration string `json:"duration,omitempty"`

	// extra info
	ExtraInfo string `json:"extra_info,omitempty"`

	// is order resource
	IsOrderResource bool `json:"is_order_resource,omitempty"`
}

// Validate validates this newbilling renew prod instance request renew params
func (m *NewbillingRenewProdInstanceRequestRenewParams) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this newbilling renew prod instance request renew params based on context it is used
func (m *NewbillingRenewProdInstanceRequestRenewParams) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *NewbillingRenewProdInstanceRequestRenewParams) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *NewbillingRenewProdInstanceRequestRenewParams) UnmarshalBinary(b []byte) error {
	var res NewbillingRenewProdInstanceRequestRenewParams
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
