// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewbillingRefreshTokenRequest 刷新TOKEN请求信息
//
// swagger:model newbillingRefreshTokenRequest
type NewbillingRefreshTokenRequest struct {

	// 接入平台ID
	AccessSysID string `json:"access_sys_id,omitempty"`

	// 要刷新的TOKEN
	Token string `json:"token,omitempty"`

	// 用户ID
	UserID string `json:"user_id,omitempty"`
}

// Validate validates this newbilling refresh token request
func (m *NewbillingRefreshTokenRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this newbilling refresh token request based on context it is used
func (m *NewbillingRefreshTokenRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *NewbillingRefreshTokenRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *NewbillingRefreshTokenRequest) UnmarshalBinary(b []byte) error {
	var res NewbillingRefreshTokenRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
