// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewbillingIamAccessSystem 接入系统
//
// swagger:model newbillingIamAccessSystem
type NewbillingIamAccessSystem struct {

	// 接入系统别名
	AccessSysCode string `json:"access_sys_code,omitempty"`

	// 接入系统ID
	AccessSysID string `json:"access_sys_id,omitempty"`

	// 接入系统名称
	Name string `json:"name,omitempty"`
}

// Validate validates this newbilling iam access system
func (m *NewbillingIamAccessSystem) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this newbilling iam access system based on context it is used
func (m *NewbillingIamAccessSystem) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *NewbillingIamAccessSystem) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *NewbillingIamAccessSystem) UnmarshalBinary(b []byte) error {
	var res NewbillingIamAccessSystem
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
