// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewbillingModifyComponentRequest 修改计费项请求信息
//
// swagger:model newbillingModifyComponentRequest
type NewbillingModifyComponentRequest struct {

	// 接入系统ID仅super user有效，接入系统管理员/成员会默认用当前登陆的接入系统
	AccessSysID string `json:"access_sys_id,omitempty"`

	// 计费项编码
	CompCode string `json:"comp_code,omitempty"`

	// 计费项ID   @gotags: valid:"Required"
	CompID string `json:"comp_id,omitempty"`

	// 计费项描述
	Description string `json:"description,omitempty"`

	// 计费项名称   @gotags: valid:"MaxSize(30)"
	Name string `json:"name,omitempty"`

	// 方案ID
	PlanID string `json:"plan_id,omitempty"`

	// 产品ID
	ProdID string `json:"prod_id,omitempty"`
}

// Validate validates this newbilling modify component request
func (m *NewbillingModifyComponentRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this newbilling modify component request based on context it is used
func (m *NewbillingModifyComponentRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *NewbillingModifyComponentRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *NewbillingModifyComponentRequest) UnmarshalBinary(b []byte) error {
	var res NewbillingModifyComponentRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
