// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewbillingCalculatePriceResponse newbilling calculate price response
//
// swagger:model newbillingCalculatePriceResponse
type NewbillingCalculatePriceResponse struct {

	// plan pricing
	PlanPricing *NewbillingPlanPricing `json:"plan_pricing,omitempty"`

	// prod code
	ProdCode string `json:"prod_code,omitempty"`

	// 产品ID
	ProdID string `json:"prod_id,omitempty"`

	// product
	Product *NewbillingProduct `json:"product,omitempty"`

	// product final price
	ProductFinalPrice float32 `json:"product_final_price,omitempty"`

	// product price
	ProductPrice float32 `json:"product_price,omitempty"`
}

// Validate validates this newbilling calculate price response
func (m *NewbillingCalculatePriceResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validatePlanPricing(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateProduct(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *NewbillingCalculatePriceResponse) validatePlanPricing(formats strfmt.Registry) error {
	if swag.IsZero(m.PlanPricing) { // not required
		return nil
	}

	if m.PlanPricing != nil {
		if err := m.PlanPricing.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("plan_pricing")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("plan_pricing")
			}
			return err
		}
	}

	return nil
}

func (m *NewbillingCalculatePriceResponse) validateProduct(formats strfmt.Registry) error {
	if swag.IsZero(m.Product) { // not required
		return nil
	}

	if m.Product != nil {
		if err := m.Product.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("product")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("product")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this newbilling calculate price response based on the context it is used
func (m *NewbillingCalculatePriceResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidatePlanPricing(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateProduct(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *NewbillingCalculatePriceResponse) contextValidatePlanPricing(ctx context.Context, formats strfmt.Registry) error {

	if m.PlanPricing != nil {
		if err := m.PlanPricing.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("plan_pricing")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("plan_pricing")
			}
			return err
		}
	}

	return nil
}

func (m *NewbillingCalculatePriceResponse) contextValidateProduct(ctx context.Context, formats strfmt.Registry) error {

	if m.Product != nil {
		if err := m.Product.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("product")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("product")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *NewbillingCalculatePriceResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *NewbillingCalculatePriceResponse) UnmarshalBinary(b []byte) error {
	var res NewbillingCalculatePriceResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
